[libdefaults]
    default_ccache_name = KCM:
    kcm_socket = /run/.heim_org.h5l.kcm-socket
    dns_lookup_realm = true
    dns_lookup_kdc = true
    dns_canonicalize_hostname = fallback
    rdns = false
