pub mod browse;
mod call_options;
mod certificate_file_problem;
mod client_identity;
pub mod column;
mod commit;
mod config_error;
mod connection;
pub mod credentials;
pub mod ddl;
pub mod dialect;
pub mod dml;
mod driver;
pub mod edit;
mod engine_stop;
mod error;
mod error_category;
pub mod export;
mod file_endpoint;
mod file_open_mode;
pub mod filter;
pub mod foreign_key_info;
pub mod hex;
mod liveness_policy;
mod loss_phase;
pub mod meta;
mod network_endpoint;
mod owned_calls;
mod query;
pub mod query_result;
mod read_only;
mod read_only_refusal;
mod registry;
pub mod save;
mod server_diagnostics;
mod server_name_override;
mod session_fate;
pub mod sql_ddl;
pub mod sql_dialect;
pub mod sql_syntax;
mod ssh_failure;
pub mod statement;
mod stop_request;
mod timeout_phase;
mod tls_capabilities;
mod tls_config;
mod tls_failure;
mod tls_mode;
mod transport;
mod transport_class;
mod transport_error;
mod transport_kind;
mod transport_route;
pub mod value;
mod write_ledger;
mod write_report;

pub use call_options::CallOptions;
pub use certificate_file_problem::CertificateFileProblem;
pub use client_identity::ClientIdentity;
pub use column::ColumnInfo;
pub use commit::{CommitResolution, CommitToken};
pub use config_error::ConfigError;
pub use connection::{AuthMode, ConnectOptions, Connection};
pub use driver::DatabaseDriver;
pub use engine_stop::{CallResource, EngineStop, StopDelivery, StopScope};
pub use error::DriverError;
pub use error_category::ErrorCategory;
pub use file_endpoint::FileEndpoint;
pub use file_open_mode::FileOpenMode;
pub use filter::{
    BuildFilterError, Combinator, FilterOp, FilterRule, FilterSet, FilterValue, build_filter, operators_for,
};
pub use liveness_policy::LivenessPolicy;
pub use loss_phase::LossPhase;
pub use network_endpoint::NetworkEndpoint;
pub use owned_calls::OwnedCalls;
pub use query::{ExecResult, ForeignKeyInfo, IndexInfo, TableInfo};
pub use query_result::QueryResult;
pub use value::Value;

/// Default upper bound on rows an arbitrary SQL query materialises.
/// Paging uses its caller's own limit and is not capped here.
pub const MAX_QUERY_ROWS: usize = 10_000;
pub use read_only::ReadOnlyConnection;
pub use read_only_refusal::ReadOnlyRefusal;
pub use registry::DriverRegistry;
pub use server_diagnostics::{ServerCode, ServerDiagnostics};
pub use server_name_override::ServerNameOverride;
pub use session_fate::SessionFate;
pub use ssh_failure::SshFailure;
pub use stop_request::{StopReason, StopRequest};
pub use timeout_phase::TimeoutPhase;
pub use tls_capabilities::TlsCapabilities;
pub use tls_config::TlsConfig;
pub use tls_failure::TlsFailure;
pub use tls_mode::TlsMode;
pub use transport::{Transport, TransportStream};
pub use transport_class::TransportClass;
pub use transport_error::TransportError;
pub use transport_kind::TransportKind;
pub use transport_route::TransportRoute;
pub use write_ledger::{WriteAtomicity, WriteLedger};
pub use write_report::{StatementOutcome, WriteReport};
