import Foundation

extension LibrarySymbolCatalog {
    static let entries: [LibrarySymbol] = [
        LibrarySymbol("cylinder", .databaseAndStorage, String(localized: "Database"), ["database", "db", "sql", "storage"]),
        LibrarySymbol("cylinder.split.1x2", .databaseAndStorage, String(localized: "Shard"), ["shard", "partition", "replica", "split"]),
        LibrarySymbol("externaldrive", .databaseAndStorage, String(localized: "External Drive"), ["disk", "drive", "volume", "storage"]),
        LibrarySymbol("internaldrive", .databaseAndStorage, String(localized: "Internal Drive"), ["disk", "hdd", "ssd", "local"]),
        LibrarySymbol("externaldrive.connected.to.line.below", .databaseAndStorage, String(localized: "Network Drive"), ["network drive", "nas", "mount", "shared"]),
        LibrarySymbol("archivebox", .databaseAndStorage, String(localized: "Archive"), ["archive", "backup", "cold storage"]),
        LibrarySymbol("tray.2", .databaseAndStorage, String(localized: "Queue"), ["queue", "inbox", "stack"]),
        LibrarySymbol("tray.full", .databaseAndStorage, String(localized: "Full Tray"), ["queue", "messages", "inbox", "full"]),
        LibrarySymbol("shippingbox", .databaseAndStorage, String(localized: "Package"), ["package", "container", "docker", "artifact"]),
        LibrarySymbol("cube", .databaseAndStorage, String(localized: "Object"), ["object", "entity", "model", "3d"]),
        LibrarySymbol("cube.transparent", .databaseAndStorage, String(localized: "Schema"), ["schema", "model", "blueprint", "structure"]),
        LibrarySymbol("square.stack.3d.up", .databaseAndStorage, String(localized: "Stack"), ["layers", "stack", "replicas", "cluster"]),
        LibrarySymbol("square.3.layers.3d", .databaseAndStorage, String(localized: "Layers"), ["layers", "tiers", "levels", "stack"]),
        LibrarySymbol("tablecells", .databaseAndStorage, String(localized: "Table"), ["table", "grid", "rows", "spreadsheet"]),
        LibrarySymbol("list.bullet.rectangle", .databaseAndStorage, String(localized: "Records"), ["records", "rows", "list"]),
        LibrarySymbol("doc.text", .databaseAndStorage, String(localized: "Document"), ["document", "file", "sqlite", "text"]),
        LibrarySymbol("doc.on.doc", .databaseAndStorage, String(localized: "Copies"), ["copy", "clone", "duplicate", "replica"]),
        LibrarySymbol("folder", .databaseAndStorage, String(localized: "Folder"), ["folder", "directory", "files"]),
        LibrarySymbol("books.vertical", .databaseAndStorage, String(localized: "Library"), ["library", "catalog", "collection"]),
        LibrarySymbol("book.closed", .databaseAndStorage, String(localized: "Ledger"), ["ledger", "docs", "manual", "journal"]),
        LibrarySymbol("memorychip", .databaseAndStorage, String(localized: "Memory"), ["memory", "ram", "cache", "redis"]),
        LibrarySymbol("clock.arrow.circlepath", .databaseAndStorage, String(localized: "History"), ["history", "backup", "snapshot", "restore"]),

        LibrarySymbol("server.rack", .serversAndNetwork, String(localized: "Server"), ["server", "rack", "datacenter", "host", "on premise"]),
        LibrarySymbol("cpu", .serversAndNetwork, String(localized: "Processor"), ["cpu", "compute", "processor", "worker"]),
        LibrarySymbol("desktopcomputer", .serversAndNetwork, String(localized: "Desktop"), ["desktop", "workstation", "local", "computer"]),
        LibrarySymbol("laptopcomputer", .serversAndNetwork, String(localized: "Laptop"), ["laptop", "local", "machine"]),
        LibrarySymbol("display", .serversAndNetwork, String(localized: "Display"), ["monitor", "screen", "dashboard"]),
        LibrarySymbol("cloud", .serversAndNetwork, String(localized: "Cloud"), ["cloud", "hosted", "saas", "managed"]),
        LibrarySymbol("network", .serversAndNetwork, String(localized: "Network"), ["network", "nodes", "topology", "cluster"]),
        LibrarySymbol("globe", .serversAndNetwork, String(localized: "Globe"), ["web", "internet", "global", "public"]),
        LibrarySymbol("antenna.radiowaves.left.and.right", .serversAndNetwork, String(localized: "Antenna"), ["remote", "wireless", "broadcast", "signal"]),
        LibrarySymbol("wifi", .serversAndNetwork, String(localized: "Wi-Fi"), ["wifi", "wireless", "network"]),
        LibrarySymbol("cable.connector", .serversAndNetwork, String(localized: "Cable"), ["cable", "connector", "port", "wired"]),
        LibrarySymbol("point.3.connected.trianglepath.dotted", .serversAndNetwork, String(localized: "Mesh"), ["graph", "nodes", "mesh", "distributed"]),
        LibrarySymbol("point.topleft.down.curvedto.point.bottomright.up", .serversAndNetwork, String(localized: "Route"), ["route", "path", "tunnel", "ssh", "proxy"]),
        LibrarySymbol("dot.radiowaves.left.and.right", .serversAndNetwork, String(localized: "Broadcast"), ["broadcast", "stream", "live", "pubsub"]),
        LibrarySymbol("rectangle.connected.to.line.below", .serversAndNetwork, String(localized: "Device"), ["device", "endpoint", "connected"]),
        LibrarySymbol("square.grid.3x3", .serversAndNetwork, String(localized: "Grid"), ["grid", "nodes", "cluster", "pool"]),
        LibrarySymbol("square.grid.2x2", .serversAndNetwork, String(localized: "Modules"), ["modules", "services", "apps"]),
        LibrarySymbol("rectangle.3.group", .serversAndNetwork, String(localized: "Services"), ["services", "microservices", "group"]),
        LibrarySymbol("arrow.left.arrow.right", .serversAndNetwork, String(localized: "Transfer"), ["sync", "transfer", "replication", "exchange"]),
        LibrarySymbol("arrow.triangle.2.circlepath", .serversAndNetwork, String(localized: "Sync"), ["sync", "refresh", "replication", "mirror"]),

        LibrarySymbol("flame", .environmentsAndStatus, String(localized: "Flame"), ["production", "prod", "live", "hot", "fire"]),
        LibrarySymbol("bolt", .environmentsAndStatus, String(localized: "Bolt"), ["live", "fast", "power", "critical"]),
        LibrarySymbol("leaf", .environmentsAndStatus, String(localized: "Leaf"), ["development", "dev", "green", "sandbox"]),
        LibrarySymbol("hammer", .environmentsAndStatus, String(localized: "Hammer"), ["build", "development", "dev", "staging"]),
        LibrarySymbol("testtube.2", .environmentsAndStatus, String(localized: "Test Tubes"), ["testing", "test", "qa", "lab"]),
        LibrarySymbol("ladybug", .environmentsAndStatus, String(localized: "Bug"), ["debug", "bug", "qa"]),
        LibrarySymbol("eye", .environmentsAndStatus, String(localized: "Eye"), ["read only", "readonly", "monitor", "view"]),
        LibrarySymbol("eye.slash", .environmentsAndStatus, String(localized: "Hidden"), ["hidden", "private", "internal"]),
        LibrarySymbol("sparkles", .environmentsAndStatus, String(localized: "Sparkles"), ["new", "fresh", "clean", "demo"]),
        LibrarySymbol("wand.and.stars", .environmentsAndStatus, String(localized: "Wand"), ["demo", "sandbox", "playground", "magic"]),
        LibrarySymbol("exclamationmark.triangle", .environmentsAndStatus, String(localized: "Warning"), ["warning", "danger", "caution", "careful"]),
        LibrarySymbol("exclamationmark.octagon", .environmentsAndStatus, String(localized: "Alert"), ["critical", "danger", "stop"]),
        LibrarySymbol("xmark.octagon", .environmentsAndStatus, String(localized: "Stop Sign"), ["blocked", "deprecated", "stop", "disabled"]),
        LibrarySymbol("checkmark.seal", .environmentsAndStatus, String(localized: "Verified"), ["verified", "approved", "stable", "certified"]),
        LibrarySymbol("checkmark.circle", .environmentsAndStatus, String(localized: "Checkmark"), ["ok", "healthy", "done", "ready"]),
        LibrarySymbol("play.circle", .environmentsAndStatus, String(localized: "Play"), ["running", "live", "active", "start"]),
        LibrarySymbol("pause.circle", .environmentsAndStatus, String(localized: "Pause"), ["paused", "idle", "suspended"]),
        LibrarySymbol("stop.circle", .environmentsAndStatus, String(localized: "Stop"), ["stopped", "halted", "offline"]),
        LibrarySymbol("flag", .environmentsAndStatus, String(localized: "Flag"), ["flag", "marker", "milestone", "important"]),
        LibrarySymbol("flag.checkered", .environmentsAndStatus, String(localized: "Checkered Flag"), ["release", "finish", "done", "launch"]),
        LibrarySymbol("tortoise", .environmentsAndStatus, String(localized: "Tortoise"), ["slow", "legacy", "old"]),
        LibrarySymbol("hare", .environmentsAndStatus, String(localized: "Hare"), ["fast", "speed", "cache", "quick"]),
        LibrarySymbol("snowflake", .environmentsAndStatus, String(localized: "Snowflake"), ["frozen", "cold", "archive", "readonly"]),
        LibrarySymbol("moon", .environmentsAndStatus, String(localized: "Moon"), ["night", "nightly", "idle", "sleep"]),
        LibrarySymbol("sun.max", .environmentsAndStatus, String(localized: "Sun"), ["day", "daily", "light", "active"]),

        LibrarySymbol("lock", .securityAndAccess, String(localized: "Lock"), ["locked", "secure", "encrypted", "private"]),
        LibrarySymbol("lock.open", .securityAndAccess, String(localized: "Unlocked"), ["unlocked", "open", "public"]),
        LibrarySymbol("lock.shield", .securityAndAccess, String(localized: "Lock Shield"), ["security", "protected", "encrypted", "vault"]),
        LibrarySymbol("key", .securityAndAccess, String(localized: "Key"), ["key", "credentials", "password", "secret"]),
        LibrarySymbol("shield", .securityAndAccess, String(localized: "Shield"), ["shield", "security", "protected", "guard"]),
        LibrarySymbol("checkmark.shield", .securityAndAccess, String(localized: "Trusted"), ["secure", "trusted", "verified", "ssl"]),
        LibrarySymbol("exclamationmark.shield", .securityAndAccess, String(localized: "Risk"), ["risk", "insecure", "alert", "audit"]),
        LibrarySymbol("bolt.shield", .securityAndAccess, String(localized: "Firewall"), ["firewall", "defense", "protected"]),
        LibrarySymbol("shield.lefthalf.filled", .securityAndAccess, String(localized: "Half Shield"), ["partial", "security", "mask"]),
        LibrarySymbol("hand.raised", .securityAndAccess, String(localized: "Raised Hand"), ["careful", "restricted", "privacy", "stop"]),
        LibrarySymbol("person.badge.shield.checkmark", .securityAndAccess, String(localized: "Admin"), ["admin", "verified", "owner", "role"]),
        LibrarySymbol("lock.rectangle", .securityAndAccess, String(localized: "Vault"), ["vault", "locked", "secure"]),
        LibrarySymbol("key.horizontal", .securityAndAccess, String(localized: "Token"), ["token", "api key", "secret", "auth"]),

        LibrarySymbol("chart.bar", .dataAndAnalytics, String(localized: "Bar Chart"), ["chart", "bar", "stats", "analytics"]),
        LibrarySymbol("chart.bar.xaxis", .dataAndAnalytics, String(localized: "Histogram"), ["histogram", "metrics", "chart"]),
        LibrarySymbol("chart.pie", .dataAndAnalytics, String(localized: "Pie Chart"), ["pie", "share", "distribution", "analytics"]),
        LibrarySymbol("chart.xyaxis.line", .dataAndAnalytics, String(localized: "Line Chart"), ["timeseries", "line chart", "metrics"]),
        LibrarySymbol("chart.line.uptrend.xyaxis", .dataAndAnalytics, String(localized: "Uptrend"), ["growth", "trend", "revenue", "kpi"]),
        LibrarySymbol("chart.line.downtrend.xyaxis", .dataAndAnalytics, String(localized: "Downtrend"), ["decline", "trend", "loss"]),
        LibrarySymbol("chart.dots.scatter", .dataAndAnalytics, String(localized: "Scatter Plot"), ["scatter", "points", "ml", "data science"]),
        LibrarySymbol("waveform.path.ecg", .dataAndAnalytics, String(localized: "Heartbeat"), ["monitoring", "health", "heartbeat", "uptime"]),
        LibrarySymbol("waveform", .dataAndAnalytics, String(localized: "Waveform"), ["signal", "stream", "audio", "logs"]),
        LibrarySymbol("gauge", .dataAndAnalytics, String(localized: "Gauge"), ["performance", "load", "metrics", "usage"]),
        LibrarySymbol("speedometer", .dataAndAnalytics, String(localized: "Speedometer"), ["speed", "benchmark", "performance"]),
        LibrarySymbol("sum", .dataAndAnalytics, String(localized: "Sum"), ["sum", "aggregate", "total"]),
        LibrarySymbol("function", .dataAndAnalytics, String(localized: "Function"), ["function", "formula", "lambda", "compute"]),
        LibrarySymbol("percent", .dataAndAnalytics, String(localized: "Percent"), ["percent", "ratio", "rate"]),
        LibrarySymbol("number", .dataAndAnalytics, String(localized: "Number"), ["number", "id", "count", "hash"]),
        LibrarySymbol("magnifyingglass", .dataAndAnalytics, String(localized: "Magnifying Glass"), ["search", "query", "explore", "lookup"]),
        LibrarySymbol("line.3.horizontal.decrease.circle", .dataAndAnalytics, String(localized: "Filter"), ["filter", "funnel", "segment"]),
        LibrarySymbol("list.number", .dataAndAnalytics, String(localized: "Numbered List"), ["ordered", "ranking", "top"]),
        LibrarySymbol("text.magnifyingglass", .dataAndAnalytics, String(localized: "Text Search"), ["full text", "search", "logs"]),
        LibrarySymbol("doc.text.magnifyingglass", .dataAndAnalytics, String(localized: "Audit"), ["audit", "inspect", "logs", "review"]),
        LibrarySymbol("chart.bar.doc.horizontal", .dataAndAnalytics, String(localized: "Report"), ["report", "dashboard", "summary"]),
        LibrarySymbol("dollarsign.circle", .dataAndAnalytics, String(localized: "Dollar"), ["money", "finance", "billing", "revenue"]),
        LibrarySymbol("creditcard", .dataAndAnalytics, String(localized: "Credit Card"), ["payments", "billing", "card", "stripe"]),
        LibrarySymbol("banknote", .dataAndAnalytics, String(localized: "Banknote"), ["cash", "payments", "finance", "accounting"]),

        LibrarySymbol("terminal", .development, String(localized: "Terminal"), ["terminal", "shell", "console", "cli"]),
        LibrarySymbol("chevron.left.forwardslash.chevron.right", .development, String(localized: "Code"), ["code", "source", "html", "dev"]),
        LibrarySymbol("curlybraces", .development, String(localized: "Braces"), ["json", "code", "nosql", "document"]),
        LibrarySymbol("curlybraces.square", .development, String(localized: "JSON"), ["json", "object", "schema"]),
        LibrarySymbol("gearshape", .development, String(localized: "Gear"), ["settings", "config", "system"]),
        LibrarySymbol("gearshape.2", .development, String(localized: "Gears"), ["automation", "services", "config", "jobs"]),
        LibrarySymbol("wrench.and.screwdriver", .development, String(localized: "Tools"), ["maintenance", "tools", "admin", "ops"]),
        LibrarySymbol("wrench", .development, String(localized: "Wrench"), ["fix", "maintenance", "tools"]),
        LibrarySymbol("puzzlepiece", .development, String(localized: "Puzzle Piece"), ["plugin", "extension", "module", "integration"]),
        LibrarySymbol("doc.badge.gearshape", .development, String(localized: "Config File"), ["config file", "settings", "env"]),
        LibrarySymbol("app", .development, String(localized: "App"), ["app", "application", "service"]),
        LibrarySymbol("macwindow", .development, String(localized: "Window"), ["window", "gui", "desktop app"]),
        LibrarySymbol("command", .development, String(localized: "Command"), ["command", "shortcut", "mac"]),
        LibrarySymbol("link", .development, String(localized: "Link"), ["link", "url", "connection string"]),
        LibrarySymbol("paperplane", .development, String(localized: "Paper Plane"), ["deploy", "send", "publish", "ship"]),
        LibrarySymbol("arrow.triangle.branch", .development, String(localized: "Branch"), ["branch", "git", "fork", "feature"]),
        LibrarySymbol("arrow.triangle.merge", .development, String(localized: "Merge"), ["merge", "pull request", "git"]),
        LibrarySymbol("arrow.triangle.pull", .development, String(localized: "Pull Request"), ["pull request", "diff", "git"]),
        LibrarySymbol("tray.and.arrow.down", .development, String(localized: "Import"), ["import", "ingest", "inbox", "etl"]),
        LibrarySymbol("tray.and.arrow.up", .development, String(localized: "Export"), ["export", "outbox", "publish"]),
        LibrarySymbol("atom", .development, String(localized: "Atom"), ["react", "science", "core", "physics"]),
        LibrarySymbol("brain", .development, String(localized: "Brain"), ["ai", "ml", "model", "intelligence"]),
        LibrarySymbol("lightbulb", .development, String(localized: "Light Bulb"), ["idea", "experiment", "prototype"]),
        LibrarySymbol("paintbrush", .development, String(localized: "Paintbrush"), ["design", "frontend", "theme", "ui"]),

        LibrarySymbol("briefcase", .workAndPlaces, String(localized: "Briefcase"), ["work", "business", "client", "job"]),
        LibrarySymbol("building", .workAndPlaces, String(localized: "Building"), ["office", "company", "branch"]),
        LibrarySymbol("building.2", .workAndPlaces, String(localized: "Office Buildings"), ["enterprise", "company", "headquarters", "corp"]),
        LibrarySymbol("building.columns", .workAndPlaces, String(localized: "Institution"), ["bank", "government", "finance", "institution"]),
        LibrarySymbol("house", .workAndPlaces, String(localized: "House"), ["home", "local", "personal"]),
        LibrarySymbol("person", .workAndPlaces, String(localized: "Person"), ["personal", "user", "me", "owner"]),
        LibrarySymbol("person.2", .workAndPlaces, String(localized: "Two People"), ["team", "shared", "pair", "users"]),
        LibrarySymbol("person.3", .workAndPlaces, String(localized: "Team"), ["group", "organization", "department"]),
        LibrarySymbol("person.crop.circle", .workAndPlaces, String(localized: "Account"), ["account", "profile", "customer"]),
        LibrarySymbol("graduationcap", .workAndPlaces, String(localized: "Graduation Cap"), ["school", "education", "training", "course"]),
        LibrarySymbol("book", .workAndPlaces, String(localized: "Book"), ["docs", "wiki", "reading"]),
        LibrarySymbol("newspaper", .workAndPlaces, String(localized: "Newspaper"), ["news", "blog", "content", "cms"]),
        LibrarySymbol("envelope", .workAndPlaces, String(localized: "Envelope"), ["email", "mail", "newsletter", "smtp"]),
        LibrarySymbol("phone", .workAndPlaces, String(localized: "Phone"), ["phone", "mobile", "support", "call"]),
        LibrarySymbol("bubble.left.and.bubble.right", .workAndPlaces, String(localized: "Chat"), ["chat", "messaging", "support", "forum"]),
        LibrarySymbol("cart", .workAndPlaces, String(localized: "Cart"), ["shop", "ecommerce", "orders", "store"]),
        LibrarySymbol("bag", .workAndPlaces, String(localized: "Bag"), ["retail", "shop", "store", "products"]),
        LibrarySymbol("tag", .workAndPlaces, String(localized: "Tag"), ["tag", "label", "pricing", "product"]),
        LibrarySymbol("gift", .workAndPlaces, String(localized: "Gift"), ["rewards", "promo", "loyalty"]),
        LibrarySymbol("ticket", .workAndPlaces, String(localized: "Ticket"), ["ticket", "issues", "events", "booking"]),
        LibrarySymbol("airplane", .workAndPlaces, String(localized: "Airplane"), ["travel", "flights", "airline"]),
        LibrarySymbol("car", .workAndPlaces, String(localized: "Car"), ["car", "vehicle", "fleet", "transport"]),
        LibrarySymbol("bus", .workAndPlaces, String(localized: "Bus"), ["transit", "transport", "logistics"]),
        LibrarySymbol("map", .workAndPlaces, String(localized: "Map"), ["map", "geo", "gis", "maps"]),
        LibrarySymbol("mappin", .workAndPlaces, String(localized: "Map Pin"), ["location", "place", "store", "geo"]),
        LibrarySymbol("globe.americas", .workAndPlaces, String(localized: "Americas"), ["americas", "us", "region"]),
        LibrarySymbol("globe.europe.africa", .workAndPlaces, String(localized: "Europe and Africa"), ["europe", "eu", "africa", "region"]),
        LibrarySymbol("globe.asia.australia", .workAndPlaces, String(localized: "Asia and Australia"), ["asia", "apac", "australia", "region"]),
        LibrarySymbol("cross.case", .workAndPlaces, String(localized: "Medical Case"), ["medical", "health", "clinic", "hospital"]),
        LibrarySymbol("cup.and.saucer", .workAndPlaces, String(localized: "Coffee Cup"), ["cafe", "coffee", "break"]),
        LibrarySymbol("fork.knife", .workAndPlaces, String(localized: "Fork and Knife"), ["restaurant", "food", "menu"]),
        LibrarySymbol("gamecontroller", .workAndPlaces, String(localized: "Game Controller"), ["games", "gaming", "player"]),
        LibrarySymbol("music.note", .workAndPlaces, String(localized: "Music"), ["music", "audio", "songs"]),
        LibrarySymbol("film", .workAndPlaces, String(localized: "Film"), ["video", "movies", "media"]),
        LibrarySymbol("photo", .workAndPlaces, String(localized: "Photo"), ["photos", "images", "media", "assets"]),

        LibrarySymbol("star", .symbolsAndObjects, String(localized: "Star"), ["star", "favorite", "important"]),
        LibrarySymbol("heart", .symbolsAndObjects, String(localized: "Heart"), ["heart", "favorite", "love", "health"]),
        LibrarySymbol("circle", .symbolsAndObjects, String(localized: "Circle"), ["circle", "dot", "round"]),
        LibrarySymbol("square", .symbolsAndObjects, String(localized: "Square"), ["square", "box"]),
        LibrarySymbol("triangle", .symbolsAndObjects, String(localized: "Triangle"), ["triangle", "delta"]),
        LibrarySymbol("diamond", .symbolsAndObjects, String(localized: "Diamond"), ["diamond", "gem"]),
        LibrarySymbol("hexagon", .symbolsAndObjects, String(localized: "Hexagon"), ["hexagon", "cell", "honeycomb"]),
        LibrarySymbol("seal", .symbolsAndObjects, String(localized: "Seal"), ["seal", "badge", "stamp"]),
        LibrarySymbol("crown", .symbolsAndObjects, String(localized: "Crown"), ["crown", "primary", "main", "king"]),
        LibrarySymbol("rosette", .symbolsAndObjects, String(localized: "Rosette"), ["award", "badge", "best"]),
        LibrarySymbol("trophy", .symbolsAndObjects, String(localized: "Trophy"), ["trophy", "winner", "achievement"]),
        LibrarySymbol("bookmark", .symbolsAndObjects, String(localized: "Bookmark"), ["bookmark", "saved", "pinned"]),
        LibrarySymbol("pin", .symbolsAndObjects, String(localized: "Pin"), ["pin", "pinned", "sticky"]),
        LibrarySymbol("bell", .symbolsAndObjects, String(localized: "Bell"), ["alerts", "notifications", "alarm"]),
        LibrarySymbol("staroflife", .symbolsAndObjects, String(localized: "Star of Life"), ["emergency", "medical", "critical"]),
        LibrarySymbol("infinity", .symbolsAndObjects, String(localized: "Infinity"), ["infinite", "forever", "loop"]),
        LibrarySymbol("1.circle", .symbolsAndObjects, String(localized: "Number 1"), ["one", "first", "primary", "1"]),
        LibrarySymbol("2.circle", .symbolsAndObjects, String(localized: "Number 2"), ["two", "second", "secondary", "2"]),
        LibrarySymbol("3.circle", .symbolsAndObjects, String(localized: "Number 3"), ["three", "third", "3"]),
        LibrarySymbol("4.circle", .symbolsAndObjects, String(localized: "Number 4"), ["four", "fourth", "4"]),
        LibrarySymbol("5.circle", .symbolsAndObjects, String(localized: "Number 5"), ["five", "fifth", "5"]),
        LibrarySymbol("pawprint", .symbolsAndObjects, String(localized: "Paw Print"), ["pet", "animal", "paw"]),
        LibrarySymbol("fish", .symbolsAndObjects, String(localized: "Fish"), ["fish", "ocean", "sea"]),
        LibrarySymbol("mountain.2", .symbolsAndObjects, String(localized: "Mountains"), ["mountain", "peak", "outdoors"]),
        LibrarySymbol("drop", .symbolsAndObjects, String(localized: "Drop"), ["drop", "water", "liquid", "data lake"]),
        LibrarySymbol("cloud.sun", .symbolsAndObjects, String(localized: "Cloud and Sun"), ["weather", "forecast", "sunny"]),
        LibrarySymbol("theatermasks", .symbolsAndObjects, String(localized: "Theater Masks"), ["theater", "entertainment", "events"]),
        LibrarySymbol("dice", .symbolsAndObjects, String(localized: "Dice"), ["random", "game", "chance"]),
        LibrarySymbol("birthday.cake", .symbolsAndObjects, String(localized: "Cake"), ["birthday", "party", "celebration"]),
        LibrarySymbol("party.popper", .symbolsAndObjects, String(localized: "Party Popper"), ["party", "launch", "celebration"]),
    ]
}
