import Foundation

enum MongoVocabulary {
    static let databaseMethods: [(name: String, detail: String)] = [
        ("getCollectionNames", "Array of collection and view names"),
        ("getCollectionInfos", "Collection and view info documents"),
        ("getCollection", "Collection object for a name that is not a valid identifier"),
        ("getSiblingDB", "Switch to another database in the same connection"),
        ("createCollection", "Create a collection or view"),
        ("createView", "Create a read-only view over a pipeline"),
        ("aggregate", "Run a collectionless aggregation pipeline"),
        ("runCommand", "Run a database command"),
        ("adminCommand", "Run a command against the admin database"),
        ("stats", "Database storage statistics"),
        ("dropDatabase", "Drop the current database"),
        ("version", "Server version"),
        ("hello", "Server description and topology"),
        ("hostInfo", "Host machine information"),
        ("serverStatus", "Server status counters"),
        ("serverBuildInfo", "Server build information"),
        ("currentOp", "Operations in progress"),
        ("killOp", "Terminate an operation by opid"),
        ("getProfilingStatus", "Current profiling level"),
        ("setProfilingLevel", "Set the profiling level"),
        ("getUsers", "Users defined on this database"),
        ("getRoles", "Roles defined on this database"),
        ("createUser", "Create a user"),
        ("dropUser", "Drop a user"),
        ("createRole", "Create a role"),
        ("dropRole", "Drop a role"),
        ("watch", "Open a change stream on the database")
    ]

    static let collectionMethods: [(name: String, detail: String)] = [
        ("find", "Select documents and return a cursor"),
        ("findOne", "Return one matching document, or null"),
        ("aggregate", "Run an aggregation pipeline"),
        ("countDocuments", "Accurate count using an aggregation"),
        ("estimatedDocumentCount", "Fast approximate count from collection metadata"),
        ("distinct", "Array of distinct values for a field"),
        ("insertOne", "Insert one document"),
        ("insertMany", "Insert an array of documents"),
        ("updateOne", "Update the first matching document"),
        ("updateMany", "Update every matching document"),
        ("replaceOne", "Replace the first matching document"),
        ("deleteOne", "Delete the first matching document"),
        ("deleteMany", "Delete every matching document"),
        ("findOneAndUpdate", "Find one document, update it, return it"),
        ("findOneAndReplace", "Find one document, replace it, return it"),
        ("findOneAndDelete", "Find one document, delete it, return it"),
        ("bulkWrite", "Several write operations in one command"),
        ("createIndex", "Build an index"),
        ("createIndexes", "Build one or more indexes"),
        ("dropIndex", "Drop one index by name or key spec"),
        ("dropIndexes", "Drop the given indexes"),
        ("getIndexes", "Documents describing every index"),
        ("hideIndex", "Hide an index from the query planner"),
        ("unhideIndex", "Make a hidden index visible again"),
        ("drop", "Drop the collection and its indexes"),
        ("renameCollection", "Rename within the same database"),
        ("stats", "Collection storage statistics"),
        ("dataSize", "Uncompressed size of the documents, in bytes"),
        ("storageSize", "Bytes allocated for document storage"),
        ("totalIndexSize", "Total bytes used by all indexes"),
        ("totalSize", "Storage size plus total index size"),
        ("isCapped", "True if the collection is capped"),
        ("validate", "Validate collection and index integrity"),
        ("explain", "Return the query plan instead of results")
    ]

    /// What a cursor answers to, which is what `find()` and `aggregate()` return.
    static let cursorMethods: [(name: String, detail: String)] = [
        ("sort", "Order the results by one or more fields"),
        ("limit", "Return at most this many documents"),
        ("skip", "Skip this many documents first"),
        ("projection", "Choose which fields come back"),
        ("hint", "Name the index to use"),
        ("collation", "Language rules for string comparison"),
        ("maxTimeMS", "Give up after this many milliseconds"),
        ("batchSize", "Documents per round trip"),
        ("allowDiskUse", "Let a large sort spill to disk"),
        ("forEach", "Call a function for every document"),
        ("map", "Build an array from every document"),
        ("toArray", "Read every document into an array"),
        ("hasNext", "True while documents remain"),
        ("next", "Read the next document"),
        ("tryNext", "Read the next document, or null"),
        ("count", "Number of documents matching the query"),
        ("itcount", "Count by reading the cursor to its end"),
        ("size", "Documents remaining, after skip and limit"),
        ("explain", "Return the query plan instead of results"),
        ("pretty", "Format the documents for reading"),
        ("close", "Release the cursor"),
        ("isExhausted", "True once nothing remains"),
        ("objsLeftInBatch", "Documents left in the current batch")
    ]

    static let deprecatedCollectionMethods: Set<String> = [
        "insert", "update", "remove", "count", "findAndModify", "mapReduce", "reIndex", "ensureIndex"
    ]

    static let queryOperators: [(name: String, detail: String)] = [
        ("$eq", "Matches values equal to a specified value"),
        ("$ne", "Matches values not equal to a specified value"),
        ("$gt", "Matches values greater than a specified value"),
        ("$gte", "Matches values greater than or equal to a specified value"),
        ("$lt", "Matches values less than a specified value"),
        ("$lte", "Matches values less than or equal to a specified value"),
        ("$in", "Matches any of the values in an array"),
        ("$nin", "Matches none of the values in an array"),
        ("$and", "Joins query clauses with a logical AND"),
        ("$or", "Joins query clauses with a logical OR"),
        ("$nor", "Joins query clauses with a logical NOR"),
        ("$not", "Inverts the effect of a query expression"),
        ("$exists", "Matches documents that have the specified field"),
        ("$type", "Matches documents where a field is of the specified BSON type"),
        ("$expr", "Allows an aggregation expression inside a query predicate"),
        ("$jsonSchema", "Validates documents against the given JSON Schema"),
        ("$mod", "Performs a modulo operation on a field value"),
        ("$regex", "Selects documents where a value matches a regular expression"),
        ("$options", "Regular expression options for $regex"),
        ("$text", "Performs a text search on a text-indexed field"),
        ("$where", "Matches documents against a JavaScript predicate (deprecated in 8.0)"),
        ("$all", "Matches arrays containing all the specified elements"),
        ("$elemMatch", "Matches arrays with at least one element matching all conditions"),
        ("$size", "Matches arrays with the specified number of elements"),
        ("$bitsAllClear", "Matches where all the given bit positions are 0"),
        ("$bitsAllSet", "Matches where all the given bit positions are 1"),
        ("$bitsAnyClear", "Matches where any of the given bit positions is 0"),
        ("$bitsAnySet", "Matches where any of the given bit positions is 1"),
        ("$geoIntersects", "Matches geometries that intersect a GeoJSON geometry"),
        ("$geoWithin", "Matches geometries within a bounding geometry"),
        ("$near", "Matches points near a given point, nearest first"),
        ("$nearSphere", "Matches points near a point on a sphere, nearest first"),
        ("$geometry", "GeoJSON geometry argument for a geospatial operator"),
        ("$minDistance", "Minimum distance for $near and $nearSphere"),
        ("$maxDistance", "Maximum distance for $near and $nearSphere"),
        ("$box", "Rectangle argument for $geoWithin"),
        ("$center", "Circle argument for $geoWithin, on a flat plane"),
        ("$centerSphere", "Circle argument for $geoWithin, on a sphere"),
        ("$polygon", "Polygon argument for $geoWithin")
    ]

    static let updateOperators: [(name: String, detail: String)] = [
        ("$set", "Sets the value of a field"),
        ("$unset", "Removes the field from the document"),
        ("$setOnInsert", "Sets the field only when the update inserts a document"),
        ("$inc", "Increments the field by the specified amount"),
        ("$mul", "Multiplies the field by the specified amount"),
        ("$min", "Updates only if the specified value is less than the current one"),
        ("$max", "Updates only if the specified value is greater than the current one"),
        ("$rename", "Renames a field"),
        ("$currentDate", "Sets the field to the current date or timestamp"),
        ("$addToSet", "Adds a value to an array only if it is not already present"),
        ("$push", "Appends a value to an array"),
        ("$pull", "Removes every array element matching a condition"),
        ("$pullAll", "Removes every listed value from an array"),
        ("$pop", "Removes the first (-1) or last (1) element of an array"),
        ("$each", "Applies a push or addToSet to several values"),
        ("$position", "Insert position for a $push with $each"),
        ("$slice", "Limits the array length after a $push with $each"),
        ("$sort", "Reorders an array after a $push with $each"),
        ("$bit", "Performs a bitwise and, or, or xor on an integer field")
    ]

    static let updatePipelineStages: [(name: String, detail: String)] = [
        ("$set", "Adds or overwrites fields, as an aggregation stage"),
        ("$addFields", "Adds or overwrites fields"),
        ("$unset", "Removes the named fields"),
        ("$project", "Reshapes the document"),
        ("$replaceRoot", "Promotes a sub-document to the top level"),
        ("$replaceWith", "Promotes a sub-document to the top level")
    ]

    static let pipelineStages: [(name: String, detail: String)] = [
        ("$match", "Filters documents with a query predicate"),
        ("$group", "Groups documents and applies accumulators"),
        ("$project", "Reshapes each document"),
        ("$addFields", "Adds or overwrites fields"),
        ("$set", "Adds or overwrites fields, an alias for $addFields"),
        ("$unset", "Removes the named fields"),
        ("$sort", "Orders the documents"),
        ("$limit", "Passes the first N documents"),
        ("$skip", "Skips the first N documents"),
        ("$count", "Counts the documents into a single named field"),
        ("$lookup", "Left outer join with another collection"),
        ("$graphLookup", "Recursive search across a collection"),
        ("$unwind", "Outputs one document per array element"),
        ("$facet", "Runs several sub-pipelines over the same input"),
        ("$bucket", "Groups into buckets with explicit boundaries"),
        ("$bucketAuto", "Groups into a fixed number of computed buckets"),
        ("$sortByCount", "Groups and counts, sorted by count descending"),
        ("$replaceRoot", "Promotes a sub-document to the top level"),
        ("$replaceWith", "Promotes a sub-document to the top level"),
        ("$sample", "Selects a random sample of documents"),
        ("$unionWith", "Concatenates another collection's results"),
        ("$setWindowFields", "Computes window function output over partitions"),
        ("$densify", "Fills gaps in a numeric or date sequence"),
        ("$fill", "Populates null and missing values"),
        ("$geoNear", "Orders documents by proximity to a point"),
        ("$redact", "Restricts document content based on an expression"),
        ("$documents", "Uses literal documents as the pipeline input"),
        ("$merge", "Writes the results into a collection"),
        ("$out", "Replaces a collection with the results"),
        ("$collStats", "Collection statistics"),
        ("$indexStats", "Index usage statistics"),
        ("$planCacheStats", "Plan cache information"),
        ("$changeStream", "Opens a change stream"),
        ("$currentOp", "Operations in progress"),
        ("$listSessions", "Sessions in the system sessions collection"),
        ("$listLocalSessions", "Sessions on the current node")
    ]

    static let expressionOperators: [(name: String, detail: String)] = [
        ("$abs", "Absolute value"), ("$add", "Adds numbers or a date and numbers"),
        ("$ceil", "Rounds up to the nearest integer"), ("$divide", "Divides two numbers"),
        ("$exp", "Raises e to the given exponent"), ("$floor", "Rounds down to the nearest integer"),
        ("$ln", "Natural logarithm"), ("$log", "Logarithm in the given base"),
        ("$log10", "Base 10 logarithm"), ("$mod", "Remainder of a division"),
        ("$multiply", "Multiplies numbers"), ("$pow", "Raises a number to an exponent"),
        ("$round", "Rounds to a given number of decimal places"),
        ("$sqrt", "Square root"), ("$subtract", "Subtracts two numbers or two dates"),
        ("$trunc", "Truncates to a given number of decimal places"),
        ("$arrayElemAt", "Element at the given array index"),
        ("$arrayToObject", "Converts key/value pairs into a document"),
        ("$concatArrays", "Concatenates arrays"),
        ("$filter", "Selects array elements matching a condition"),
        ("$firstN", "First N elements of an array"), ("$lastN", "Last N elements of an array"),
        ("$indexOfArray", "Index of the first matching array element"),
        ("$isArray", "True if the argument is an array"),
        ("$map", "Applies an expression to every array element"),
        ("$maxN", "N largest values"), ("$minN", "N smallest values"),
        ("$objectToArray", "Converts a document into key/value pairs"),
        ("$range", "Generates a sequence of numbers"),
        ("$reduce", "Folds an array into a single value"),
        ("$reverseArray", "Reverses an array"), ("$size", "Number of elements in an array"),
        ("$slice", "Sub-array of an array"), ("$sortArray", "Sorts an array"),
        ("$zip", "Merges arrays element by element"),
        ("$and", "Logical AND of expressions"), ("$or", "Logical OR of expressions"),
        ("$not", "Logical NOT of an expression"),
        ("$cmp", "Compares two values and returns -1, 0 or 1"),
        ("$eq", "True if the two expressions are equal"),
        ("$ne", "True if the two expressions are not equal"),
        ("$gt", "True if the first expression is greater"),
        ("$gte", "True if the first expression is greater or equal"),
        ("$lt", "True if the first expression is less"),
        ("$lte", "True if the first expression is less or equal"),
        ("$cond", "Ternary conditional"),
        ("$ifNull", "First non-null expression"),
        ("$switch", "Evaluates branches until one case is true"),
        ("$binarySize", "Byte size of a string or binary value"),
        ("$bsonSize", "BSON byte size of a document"),
        ("$dateAdd", "Adds a time unit to a date"),
        ("$dateSubtract", "Subtracts a time unit from a date"),
        ("$dateDiff", "Difference between two dates in a time unit"),
        ("$dateFromParts", "Builds a date from its parts"),
        ("$dateToParts", "Splits a date into its parts"),
        ("$dateFromString", "Parses a date from a string"),
        ("$dateToString", "Formats a date as a string"),
        ("$dateTrunc", "Truncates a date to a time unit"),
        ("$dayOfMonth", "Day of the month"), ("$dayOfWeek", "Day of the week"),
        ("$dayOfYear", "Day of the year"), ("$hour", "Hour of the day"),
        ("$isoDayOfWeek", "ISO day of the week"), ("$isoWeek", "ISO week number"),
        ("$isoWeekYear", "ISO week-numbering year"), ("$millisecond", "Milliseconds"),
        ("$minute", "Minutes"), ("$month", "Month"), ("$second", "Seconds"),
        ("$week", "Week of the year"), ("$year", "Year"),
        ("$literal", "Returns a value without parsing it as an expression"),
        ("$getField", "Reads a field whose name needs escaping"),
        ("$setField", "Writes a field whose name needs escaping"),
        ("$unsetField", "Removes a field whose name needs escaping"),
        ("$mergeObjects", "Merges documents into one"),
        ("$rand", "Random float between 0 and 1"),
        ("$allElementsTrue", "True if every element is true"),
        ("$anyElementTrue", "True if any element is true"),
        ("$setDifference", "Elements in the first set only"),
        ("$setEquals", "True if the sets have the same distinct elements"),
        ("$setIntersection", "Elements common to every set"),
        ("$setIsSubset", "True if the first set is a subset of the second"),
        ("$setUnion", "Distinct elements of every set"),
        ("$concat", "Concatenates strings"),
        ("$indexOfBytes", "Byte index of a substring"),
        ("$indexOfCP", "Code point index of a substring"),
        ("$ltrim", "Trims characters from the start"),
        ("$rtrim", "Trims characters from the end"), ("$trim", "Trims characters from both ends"),
        ("$regexFind", "First regular expression match"),
        ("$regexFindAll", "All regular expression matches"),
        ("$regexMatch", "True if the regular expression matches"),
        ("$replaceOne", "Replaces the first occurrence of a substring"),
        ("$replaceAll", "Replaces every occurrence of a substring"),
        ("$split", "Splits a string on a delimiter"),
        ("$strLenBytes", "Length of a string in bytes"),
        ("$strLenCP", "Length of a string in code points"),
        ("$strcasecmp", "Case-insensitive string comparison"),
        ("$substrBytes", "Substring by byte offset"),
        ("$substrCP", "Substring by code point offset"),
        ("$toLower", "Lowercases a string"), ("$toUpper", "Uppercases a string"),
        ("$meta", "Reads per-document metadata such as textScore"),
        ("$tsIncrement", "Increment part of a timestamp"),
        ("$tsSecond", "Seconds part of a timestamp"),
        ("$convert", "Converts a value to the given type"),
        ("$isNumber", "True if the value is numeric"),
        ("$toBool", "Converts to a boolean"), ("$toDate", "Converts to a date"),
        ("$toDecimal", "Converts to a decimal"), ("$toDouble", "Converts to a double"),
        ("$toInt", "Converts to a 32-bit integer"), ("$toLong", "Converts to a 64-bit integer"),
        ("$toObjectId", "Converts to an ObjectId"), ("$toString", "Converts to a string"),
        ("$toUUID", "Converts to a UUID"), ("$type", "Returns the BSON type as a string"),
        ("$let", "Binds variables for use in an expression")
    ]

    static let accumulators: [(name: String, detail: String)] = [
        ("$sum", "Sum of the values"), ("$avg", "Average of the values"),
        ("$min", "Smallest value"), ("$max", "Largest value"),
        ("$first", "Value from the first document"), ("$last", "Value from the last document"),
        ("$firstN", "Values from the first N documents"),
        ("$lastN", "Values from the last N documents"),
        ("$maxN", "N largest values"), ("$minN", "N smallest values"),
        ("$push", "All values as an array"), ("$addToSet", "Distinct values as an array"),
        ("$count", "Number of documents in the group"),
        ("$median", "Approximate median"), ("$percentile", "Approximate percentiles"),
        ("$stdDevPop", "Population standard deviation"),
        ("$stdDevSamp", "Sample standard deviation"),
        ("$top", "Value from the top document by a sort order"),
        ("$topN", "Values from the top N documents by a sort order"),
        ("$bottom", "Value from the bottom document by a sort order"),
        ("$bottomN", "Values from the bottom N documents by a sort order"),
        ("$mergeObjects", "Merges the documents in the group"),
        ("$covariancePop", "Population covariance"), ("$covarianceSamp", "Sample covariance")
    ]

    static let projectionOperators: [(name: String, detail: String)] = [
        ("$elemMatch", "Projects the first array element matching a condition"),
        ("$slice", "Limits the array elements projected"),
        ("$meta", "Projects per-document metadata")
    ]

    static let systemVariables: [(name: String, detail: String)] = [
        ("$$NOW", "Current datetime, identical for the whole pipeline"),
        ("$$CLUSTER_TIME", "Current cluster timestamp"),
        ("$$ROOT", "The root document being processed"),
        ("$$CURRENT", "The start of the field path being processed"),
        ("$$REMOVE", "Evaluates to missing, so a field is excluded"),
        ("$$DESCEND", "Keep the current level and evaluate sub-documents ($redact)"),
        ("$$PRUNE", "Exclude the current level ($redact)"),
        ("$$KEEP", "Keep the current level ($redact)"),
        ("$$USER_ROLES", "Roles assigned to the current user")
    ]

    static let bsonConstructors: [(name: String, detail: String)] = [
        ("ObjectId", "12-byte ObjectId, from a 24-character hex string"),
        ("ISODate", "Date from an ISO 8601 string"),
        ("UUID", "UUID from a 36-character string, BSON binary subtype 4"),
        ("BinData", "Binary value from a subtype and a base64 string"),
        ("HexData", "Binary value from a subtype and a hex string"),
        ("Timestamp", "BSON timestamp from { t, i }"),
        ("Int32", "32-bit integer"),
        ("Long", "64-bit integer, from a string"),
        ("Double", "64-bit floating point number"),
        ("Decimal128", "IEEE 754 decimal128, from a string"),
        ("NumberInt", "32-bit integer, legacy shell name"),
        ("NumberLong", "64-bit integer, legacy shell name, string argument only"),
        ("NumberDecimal", "Decimal128, legacy shell name"),
        ("BSONRegExp", "Regular expression with options")
    ]

    static let shellCommands: [(name: String, detail: String)] = [
        ("use", "Switch the current database"),
        ("show dbs", "List databases"),
        ("show collections", "List collections in the current database"),
        ("show users", "List users on the current database"),
        ("show roles", "List roles on the current database"),
        ("show profile", "List the slowest profiled operations")
    ]

    static let bsonTypeAliases: [String] = [
        "double", "string", "object", "array", "binData", "objectId", "bool", "date", "null",
        "regex", "javascript", "int", "timestamp", "long", "decimal", "minKey", "maxKey", "number"
    ]
}
