//
//  StagedWriteScope.swift
//  TablePro
//

import Foundation

/// Where one press of Save runs.
///
/// A queued Truncate or Drop names the database it was queued against, and the plan follows that
/// rather than the tab in front. It used to take the selected tab's scope, so queueing a drop in
/// one database, switching to another and pressing Save dropped the table of that name in the
/// second one.
///
/// The statements are generated by the session's own driver before anything is pinned, and a
/// driver that qualifies from its live connection writes the database it is on into the statement:
/// Snowflake builds a three-part name from `currentDatabase`, SurrealDB opens with its current
/// namespace. Pinning the plan afterwards cannot correct a name already written, so a queue is
/// only saved from the database it was queued in, and is refused rather than rewritten anywhere
/// else. Row edits carry no such queue and keep their own tab's scope.
enum StagedWriteScope {
    static func resolve(
        tabScope: DatabaseScope,
        browseDatabase: String,
        stagedDatabases: Set<String>,
        includesRowEdits: Bool
    ) throws -> DatabaseScope {
        let staged = stagedDatabases.filter { !$0.isEmpty }
        guard !staged.isEmpty else { return tabScope }
        guard staged.count == 1, let database = staged.first else {
            throw DatabaseError.writeSpansDatabases
        }
        guard database == browseDatabase else {
            throw DatabaseError.stagedWriteOutsideBrowsedDatabase(database)
        }
        guard !includesRowEdits || tabScope.database == database else {
            throw DatabaseError.writeSpansDatabases
        }
        guard database != tabScope.database else { return tabScope }
        /// The tab's schema belongs to the tab's database and means nothing in another one. Every
        /// queued statement qualifies its own schema, so the scope does not need to carry one.
        return DatabaseScope(connectionId: tabScope.connectionId, database: database, schema: nil)
    }
}
