import Foundation
import TableProSpannerCore
import Testing

@Suite("SpannerDDLCatalog")
struct SpannerDDLCatalogTests {
    private static let googleSQLDatabase = [
        "CREATE SCHEMA sales",
        "CREATE SEQUENCE seq OPTIONS (\n  sequence_kind = 'bit_reversed_positive')",
        """
            CREATE TABLE Singers (
              Id INT64 NOT NULL,
              Name STRING(MAX),
              Age INT64,
              Active BOOL,
              Photo BYTES(MAX),
              Tags ARRAY<STRING(MAX)>,
              Born DATE,
              Updated TIMESTAMP,
              Score NUMERIC,
              Doc JSON,
              Flags ARRAY<BOOL>,
            ) PRIMARY KEY(Id)
            """,
        "CREATE INDEX SingersByName ON Singers(Name) STORING (Age)",
        "CREATE TABLE Docs (\n  Tenant STRING(36) NOT NULL,\n  K BYTES(16) NOT NULL,\n  V STRING(MAX),\n) PRIMARY KEY(Tenant, K)",
        "CREATE TABLE Parent (\n  A INT64 NOT NULL,\n  B INT64 NOT NULL,\n) PRIMARY KEY(A, B)",
        """
            CREATE TABLE Child (
              Id INT64 NOT NULL,
              X INT64,
              Y INT64,
              CONSTRAINT FK_XY FOREIGN KEY(X, Y) REFERENCES Parent(A, B),
            ) PRIMARY KEY(Id)
            """,
        """
            CREATE TABLE Albums (
              Id INT64 NOT NULL,
              AlbumId INT64 NOT NULL,
              Title STRING(MAX),
            ) PRIMARY KEY(Id, AlbumId),
              INTERLEAVE IN PARENT Singers ON DELETE CASCADE
            """,
        "CREATE TABLE sales.Orders (\n  Id INT64 NOT NULL,\n  Amt FLOAT64,\n) PRIMARY KEY(Id)",
        """
            CREATE TABLE T2 (
              Id INT64 NOT NULL,
              F FLOAT64,
              AI ARRAY<INT64>,
              AB ARRAY<BYTES(MAX)>,
              B BYTES(MAX),
              D STRING(MAX) DEFAULT ('dflt'),
              G STRING(MAX) AS (CONCAT(D, '!')) STORED,
              J JSON,
            ) PRIMARY KEY(Id)
            """,
        "CREATE TABLE T3 (\n  Id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),\n  V STRING(MAX),\n) PRIMARY KEY(Id)",
        "CREATE VIEW SingerNames SQL SECURITY INVOKER AS SELECT Singers.Id, Singers.Name FROM Singers"
    ]

    private static let postgreSQLDatabase = [
        "CREATE SCHEMA sales",
        """
            CREATE TABLE singers (
              id bigint NOT NULL,
              name character varying,
              active boolean,
              photo bytea,
              tags character varying[],
              doc jsonb,
              score numeric,
              updated timestamp with time zone,
              born date,
              PRIMARY KEY(id)
            )
            """,
        "CREATE TABLE sales.orders (\n  id bigint NOT NULL,\n  amt double precision,\n  PRIMARY KEY(id)\n)",
        "CREATE TABLE parent (\n  a bigint NOT NULL,\n  b bigint NOT NULL,\n  PRIMARY KEY(a, b)\n)",
        """
            CREATE TABLE child (
              id bigint NOT NULL,
              x bigint,
              y bigint,
              PRIMARY KEY(id),
              CONSTRAINT fk_xy FOREIGN KEY (x, y) REFERENCES parent(a, b)
            )
            """
    ]

    private static let richGoogleSQLDatabase = [
        "CREATE SCHEMA sales",
        """
            CREATE TABLE Singers (
              Id INT64 NOT NULL,
              Name STRING(MAX),
              Age INT64,
              Active BOOL,
              Photo BYTES(MAX),
              Tags ARRAY<STRING(MAX)>,
              Born DATE,
              Updated TIMESTAMP,
              Score NUMERIC,
              Doc JSON,
              F FLOAT64,
            ) PRIMARY KEY(Id)
            """,
        "CREATE UNIQUE NULL_FILTERED INDEX SingersByAgeName ON Singers(Age DESC, Name)",
        "CREATE INDEX SingersByName ON Singers(Name) STORING (Age)",
        """
            CREATE TABLE Songs (
              Id INT64 NOT NULL,
              AlbumId INT64 NOT NULL,
              TrackId INT64 NOT NULL,
              Name STRING(MAX),
            ) PRIMARY KEY(Id, AlbumId, TrackId),
              INTERLEAVE IN PARENT Albums ON DELETE NO ACTION
            """,
        """
            CREATE TABLE sales.Orders (
              Id INT64 NOT NULL,
              Amt FLOAT64,
              SingerId INT64,
              CONSTRAINT FK_OrderSinger FOREIGN KEY(SingerId) REFERENCES Singers(Id),
            ) PRIMARY KEY(Id)
            """,
        "CREATE INDEX sales.OrdersByAmt ON sales.Orders(Amt)",
        """
            CREATE TABLE sales.Items (
              Id INT64 NOT NULL,
              Line INT64 NOT NULL,
              Sku STRING(MAX),
            ) PRIMARY KEY(Id, Line),
              INTERLEAVE IN PARENT sales.Orders ON DELETE CASCADE
            """,
        "CREATE VIEW SingerNames SQL SECURITY INVOKER AS SELECT Singers.Id, Singers.Name FROM Singers",
        "CREATE VIEW sales.BigOrders SQL SECURITY INVOKER AS SELECT o.Id FROM sales.Orders AS o WHERE o.Amt > 100"
    ]

    private static let richPostgreSQLDatabase = [
        "CREATE SCHEMA sales",
        """
            CREATE TABLE singers (
              id bigint NOT NULL,
              name character varying,
              age bigint,
              active boolean,
              photo bytea,
              tags character varying[],
              doc jsonb,
              score numeric,
              updated timestamp with time zone,
              born date,
              f double precision,
              PRIMARY KEY(id)
            )
            """,
        """
            CREATE TABLE sales.orders (
              id bigint NOT NULL,
              amt double precision,
              singer_id bigint,
              PRIMARY KEY(id),
              CONSTRAINT fk_order_singer FOREIGN KEY (singer_id) REFERENCES singers(id)
            )
            """,
        "CREATE TABLE \"MixedCase\" (\n  \"Id\" bigint NOT NULL,\n  \"Val\" character varying,\n  PRIMARY KEY(\"Id\")\n)",
        "CREATE UNIQUE INDEX singers_by_age_name ON singers (age DESC, name) WHERE (age IS NOT NULL AND name IS NOT NULL)",
        "CREATE INDEX singers_by_name ON singers (name) INCLUDE (age)",
        "CREATE INDEX orders_by_amt ON sales.orders (amt)",
        "CREATE VIEW singer_names WITH (security_invoker) AS SELECT id, name FROM singers"
    ]

    @Test("GoogleSQL tables resolve by exact schema and name")
    func googleSQLTables() {
        let catalog = SpannerDDLCatalog(statements: Self.googleSQLDatabase, dialect: .googleSQL)
        #expect(catalog.tableDDL(schema: "", name: "Singers") == Self.googleSQLDatabase[2])
        #expect(catalog.tableDDL(schema: "", name: "Child") == Self.googleSQLDatabase[6])
        #expect(catalog.tableDDL(schema: "", name: "Albums") == Self.googleSQLDatabase[7])
        #expect(catalog.tableDDL(schema: "sales", name: "Orders") == Self.googleSQLDatabase[8])
        #expect(catalog.tableDDL(schema: "", name: "Orders") == nil)
        #expect(catalog.tableDDL(schema: "", name: "singers") == nil)
        #expect(catalog.tableDDL(schema: "", name: "Sing") == nil)
        #expect(catalog.tableDDL(schema: "", name: "SingerNames") == nil)
    }

    @Test("GoogleSQL indexes and views")
    func googleSQLIndexesAndViews() {
        let catalog = SpannerDDLCatalog(statements: Self.googleSQLDatabase, dialect: .googleSQL)
        #expect(catalog.indexDDL(schema: "", table: "Singers") == ["CREATE INDEX SingersByName ON Singers(Name) STORING (Age)"])
        #expect(catalog.indexDDL(schema: "", table: "Child").isEmpty)
        #expect(catalog.viewDDL(schema: "", name: "SingerNames") == Self.googleSQLDatabase[11])
        #expect(catalog.viewDDL(schema: "", name: "Singers") == nil)
    }

    @Test("PostgreSQL tables live in public unless qualified")
    func postgreSQLTables() {
        let catalog = SpannerDDLCatalog(statements: Self.postgreSQLDatabase, dialect: .postgreSQL)
        #expect(catalog.tableDDL(schema: "public", name: "singers") == Self.postgreSQLDatabase[1])
        #expect(catalog.tableDDL(schema: "sales", name: "orders") == Self.postgreSQLDatabase[2])
        #expect(catalog.tableDDL(schema: "public", name: "child") == Self.postgreSQLDatabase[4])
        #expect(catalog.tableDDL(schema: "", name: "singers") == nil)
        #expect(catalog.tableDDL(schema: "public", name: "orders") == nil)
    }

    @Test("Every index modifier and a named schema")
    func richGoogleSQL() {
        let catalog = SpannerDDLCatalog(statements: Self.richGoogleSQLDatabase, dialect: .googleSQL)
        #expect(catalog.indexDDL(schema: "", table: "Singers") == [
            "CREATE UNIQUE NULL_FILTERED INDEX SingersByAgeName ON Singers(Age DESC, Name)",
            "CREATE INDEX SingersByName ON Singers(Name) STORING (Age)"
        ])
        #expect(catalog.indexDDL(schema: "sales", table: "Orders") == ["CREATE INDEX sales.OrdersByAmt ON sales.Orders(Amt)"])
        #expect(catalog.tableDDL(schema: "sales", name: "Items") == Self.richGoogleSQLDatabase[7])
        #expect(catalog.tableDDL(schema: "", name: "Songs") == Self.richGoogleSQLDatabase[4])
        #expect(catalog.viewDDL(schema: "sales", name: "BigOrders") == Self.richGoogleSQLDatabase[9])
    }

    @Test("PostgreSQL quoted names, trailing indexes and view options")
    func richPostgreSQL() {
        let catalog = SpannerDDLCatalog(statements: Self.richPostgreSQLDatabase, dialect: .postgreSQL)
        #expect(catalog.tableDDL(schema: "public", name: "MixedCase") == Self.richPostgreSQLDatabase[3])
        #expect(catalog.tableDDL(schema: "public", name: "mixedcase") == nil)
        #expect(catalog.indexDDL(schema: "public", table: "singers") == [Self.richPostgreSQLDatabase[4], Self.richPostgreSQLDatabase[5]])
        #expect(catalog.indexDDL(schema: "sales", table: "orders") == ["CREATE INDEX orders_by_amt ON sales.orders (amt)"])
        #expect(catalog.viewDDL(schema: "public", name: "singer_names") == Self.richPostgreSQLDatabase[7])
    }

    @Test("Quoted GoogleSQL paths, IF NOT EXISTS and OR REPLACE")
    func quotedPaths() {
        let statements = [
            "CREATE TABLE IF NOT EXISTS `my table` (\n  a INT64,\n) PRIMARY KEY(a)",
            "CREATE TABLE `sales`.`Or\\`ders` (\n  Id INT64,\n) PRIMARY KEY(Id)",
            "CREATE INDEX IF NOT EXISTS Idx ON `my table`(a)",
            "CREATE OR REPLACE VIEW `sales`.V SQL SECURITY INVOKER AS SELECT 1 AS x",
            "-- leading comment\nCREATE TABLE Commented (\n  Id INT64,\n) PRIMARY KEY(Id)"
        ]
        let catalog = SpannerDDLCatalog(statements: statements, dialect: .googleSQL)
        #expect(catalog.tableDDL(schema: "", name: "my table") == statements[0])
        #expect(catalog.tableDDL(schema: "sales", name: "Or`ders") == statements[1])
        #expect(catalog.indexDDL(schema: "", table: "my table") == [statements[2]])
        #expect(catalog.viewDDL(schema: "sales", name: "V") == statements[3])
        #expect(catalog.tableDDL(schema: "", name: "Commented") == statements[4])
    }

    @Test("Statements that are not tables, indexes or views are ignored")
    func ignoresOtherStatements() {
        let catalog = SpannerDDLCatalog(
            statements: ["CREATE SCHEMA s", "CREATE SEQUENCE q OPTIONS (sequence_kind = 'bit_reversed_positive')",
                         "ALTER TABLE t ADD COLUMN c INT64", "CREATE ROLE r", ""],
            dialect: .googleSQL
        )
        #expect(catalog.tableDDL(schema: "", name: "t") == nil)
        #expect(catalog.tableDDL(schema: "", name: "s") == nil)
        #expect(catalog.viewDDL(schema: "", name: "q") == nil)
    }
}
