@testable import TableProOracleCore
import XCTest

/// The stored texts here are the ones `USER_TAB_COLS.DATA_DEFAULT` returned on Oracle 23ai for the DDL named beside
/// each, read through OracleNIO. `scripts/check-oracle-column-defaults.sh` checks the same shapes against a live server.
final class OracleColumnDefaultTests: XCTestCase {
    private func clause(
        _ storedText: String?,
        isIdentity: Bool = false,
        isVirtual: Bool = false,
        onNull: OracleDefaultOnNull = .never
    ) -> String? {
        OracleColumnDefault(storedText: storedText, isIdentity: isIdentity, isVirtual: isVirtual, onNull: onNull).clause
    }

    /// `DEFAULT 7` followed by a newline and the indentation of the next line.
    func testTrailingWhitespaceTheDDLLeftBehindIsTrimmed() {
        XCTAssertEqual(clause("7\n  "), "7")
        XCTAssertEqual(clause("7    "), "7")
        XCTAssertEqual(clause("''\n"), "''")
    }

    func testNoDefaultIsNil() {
        XCTAssertNil(clause(nil))
        XCTAssertNil(clause(""))
        XCTAssertNil(clause(" \n "))
    }

    /// `DEFAULT NULL` is stored as typed, so `default null` reads `null`. It is a default, unlike SQL NULL.
    func testAnExplicitNullDefaultReadsAsNullWhateverItsCase() {
        XCTAssertEqual(clause("null"), "NULL")
        XCTAssertEqual(clause("NULL"), "NULL")
        XCTAssertEqual(clause("Null\n  "), "NULL")
    }

    func testLiteralsAndExpressionsKeepTheirSpelling() {
        XCTAssertEqual(clause("'it''s'"), "'it''s'")
        XCTAssertEqual(clause("sys_guid()"), "sys_guid()")
        XCTAssertEqual(clause("current_timestamp"), "current_timestamp")
        XCTAssertEqual(clause("-1.5"), "-1.5")
        XCTAssertEqual(clause("(1 + 2)"), "(1 + 2)")
        XCTAssertEqual(clause("'null'"), "'null'")
    }

    /// `GENERATED BY DEFAULT AS IDENTITY` stores the sequence it draws from.
    func testAnIdentityColumnHasNoDefault() {
        XCTAssertNil(clause("\"PROBE\".\"ISEQ$$_73292\".nextval", isIdentity: true))
        XCTAssertNil(clause("\"PROBE\".\"ISEQ$$_73292\".nextval", isIdentity: true, onNull: .onInsert))
    }

    /// `GENERATED ALWAYS AS (c_zero + 1) VIRTUAL` stores its expression.
    func testAVirtualColumnHasNoDefault() {
        XCTAssertNil(clause("\"C_ZERO\"+1", isVirtual: true))
    }

    /// A sequence named in an ordinary `DEFAULT` is a default like any other.
    func testASequenceDefaultOnAnOrdinaryColumnIsKept() {
        XCTAssertEqual(clause("\"PROBE\".\"MY_SEQ\".\"NEXTVAL\""), "\"PROBE\".\"MY_SEQ\".\"NEXTVAL\"")
    }

    /// Restating `'x'` alone on a `DEFAULT ON NULL` column turned the semantics off and the column nullable, measured.
    func testADefaultOnNullKeepsItsOnNull() {
        XCTAssertEqual(clause("'x'", onNull: .onInsert), "ON NULL 'x'")
        XCTAssertEqual(clause("'u'\n  ", onNull: .onInsertAndUpdate), "ON NULL FOR INSERT AND UPDATE 'u'")
    }

    /// `default 9 -- trailing comment` with the comma on the next line keeps the comment and its newline, and the
    /// newline is what stops it commenting out the rest of a statement the value is written into.
    func testATrailingLineCommentGoesWithTheWhitespace() {
        XCTAssertEqual(clause("9 -- trailing comment\n  "), "9")
        XCTAssertEqual(clause("'--' -- dashes\n  "), "'--'")
    }

    func testABlockCommentGoes() {
        XCTAssertEqual(clause("'A' /* active */\n  "), "'A'")
        XCTAssertEqual(clause("null /* none */"), "NULL")
    }

    /// `default 1 -- one` then `+ 2` on the next line.
    func testACommentInsideAMultiLineDefaultKeepsItsNewline() {
        XCTAssertEqual(clause("1 -- one\n   + 2\n  "), "1 \n   + 2")
    }

    func testCommentMarkersInsideQuotesAreText() {
        XCTAssertEqual(clause("q'[it's -- x]' -- real\n  "), "q'[it's -- x]'")
        XCTAssertEqual(clause("nq'{a''b}'\n"), "nq'{a''b}'")
        XCTAssertEqual(clause("Q'!/* x */!'"), "Q'!/* x */!'")
        XCTAssertEqual(clause("'a /* b */ c'"), "'a /* b */ c'")
        XCTAssertEqual(clause("\"COL--NAME\" -- note\n"), "\"COL--NAME\"")
    }

    /// `q'` opens an alternative quote only at the start of a word; inside a longer name the quote is ordinary, so
    /// `'it''s'` still reads its doubled quote as an escape.
    func testAQInsideANameDoesNotOpenAnAlternativeQuote() {
        XCTAssertEqual(OracleSQLCommentStripper("seq'a''b -- c' -- d").stripped(), "seq'a''b -- c' ")
    }

    func testOnNullFollowsBothFlags() {
        XCTAssertEqual(OracleDefaultOnNull(onInsert: false, onUpdate: false), .never)
        XCTAssertEqual(OracleDefaultOnNull(onInsert: true, onUpdate: false), .onInsert)
        XCTAssertEqual(OracleDefaultOnNull(onInsert: true, onUpdate: true), .onInsertAndUpdate)
        XCTAssertEqual(OracleDefaultOnNull(onInsert: false, onUpdate: true), .never)
    }
}
