//
//  QueryResult.swift
//  TablePro
//
//  Created by Ngo Quoc Dat on 16/12/25.
//

import Foundation
import TableProPluginKit

struct QueryResult {
    let columns: [String]
    let columnTypes: [ColumnType]
    let rows: [[PluginCellValue]]
    let rowsAffected: Int
    let executionTime: TimeInterval
    let error: DatabaseError?

    /// What the elapsed time was spent on, when the driver could tell. Defaults to the elapsed
    /// number alone so a result built without one reads exactly as it always did.
    var timing: PluginQueryTiming?

    var resolvedTiming: PluginQueryTiming {
        timing ?? PluginQueryTiming(total: executionTime)
    }

    /// Whether the result was truncated due to driver-level row limits
    var isTruncated: Bool = false

    /// Optional status message from the plugin (e.g. server notices, warnings)
    var statusMessage: String?

    var columnMeta: [ResultColumnMeta]?

    var isEmpty: Bool {
        rows.isEmpty
    }

    var rowCount: Int {
        rows.count
    }

    var columnCount: Int {
        columns.count
    }

    static let empty = QueryResult(
        columns: [],
        columnTypes: [],
        rows: [],
        rowsAffected: 0,
        executionTime: 0,
        error: nil
    )
}

struct ResultColumnMeta: Sendable {
    let isPrimaryKey: Bool
    let isNullable: Bool
    let isAutoIncrement: Bool
}

/// Database error types
enum DatabaseError: Error, LocalizedError {
    case connectionFailed(String)
    case queryFailed(String)
    case invalidCredentials
    case fileNotFound(String)
    case notConnected
    case unsupportedOperation
    /// One save runs against one database, so a queue that reaches two of them cannot be one
    /// plan. It is refused rather than resolved to whichever database the tab in front happens
    /// to name, which is how a drop queued in one database used to land in another.
    case writeSpansDatabases
    /// The statements are generated by the session's driver before the plan is pinned, so a queue
    /// can only be trusted from the database it was queued in.
    case stagedWriteOutsideBrowsedDatabase(String)

    var errorDescription: String? {
        switch self {
        case .connectionFailed(let message):
            return message
        case .queryFailed(let message):
            return message
        case .invalidCredentials:
            return String(localized: "Invalid username or password")
        case .fileNotFound(let path):
            return String(format: String(localized: "Database file not found: %@"), path)
        case .notConnected:
            return String(localized: "Not connected to database")
        case .unsupportedOperation:
            return String(localized: "This operation is not supported")
        case .writeSpansDatabases:
            return String(localized: "Pending changes reach more than one database. Save or discard one database at a time.")
        case .stagedWriteOutsideBrowsedDatabase(let database):
            return String(
                format: String(localized: "Pending table changes belong to %@. Switch to that database to save them, or discard them."),
                database
            )
        }
    }
}

/// Information about a database table
struct TableInfo: Identifiable, Hashable, Sendable {
    var id: String {
        if let schema, !schema.isEmpty {
            return "\(schema).\(name)_\(type.rawValue)"
        }
        return "\(name)_\(type.rawValue)"
    }
    let name: String
    let type: TableType
    let rowCount: Int?
    let schema: String?
    let comment: String?

    enum TableType: String, Sendable {
        case table = "TABLE"
        case view = "VIEW"
        case materializedView = "MATERIALIZED VIEW"
        case foreignTable = "FOREIGN TABLE"
        case systemTable = "SYSTEM TABLE"
        case partitionedTable = "PARTITIONED TABLE"
        case externalTable = "EXTERNAL TABLE"

        /// An external table lives in a catalog outside the database, has no
        /// primary key and no row identifier to target, and rejects UPDATE and
        /// DELETE, so the grid must not offer row editing for one.
        var allowsRowEditing: Bool {
            switch self {
            case .view, .externalTable:
                return false
            case .table, .materializedView, .foreignTable, .systemTable, .partitionedTable:
                return true
            }
        }
    }

    init(name: String, type: TableType, rowCount: Int?, schema: String? = nil, comment: String? = nil) {
        self.name = name
        self.type = type
        self.rowCount = rowCount
        self.schema = schema
        self.comment = comment
    }

    static func == (lhs: TableInfo, rhs: TableInfo) -> Bool {
        lhs.name == rhs.name && lhs.type == rhs.type && lhs.schema == rhs.schema
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(type)
        hasher.combine(schema)
    }
}

/// Information about a table column
struct ColumnInfo: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let dataType: String
    let isNullable: Bool
    let isPrimaryKey: Bool
    let defaultValue: String?
    let extra: String?
    let charset: String?
    let collation: String?
    let comment: String?
    /// Set when the server allocates the value from a sequence it owns, which it reports separately
    /// from the column default: PostgreSQL leaves `column_default` null for an identity column and
    /// puts the generation in `pg_attribute.attidentity`. Dropping it here made every identity
    /// column look like a column with no default.
    let identityKind: IdentityKind?
    let isGenerated: Bool
    let allowedValues: [String]?
    let generationExpression: String?
    let generationKind: GenerationKind?

    init(
        name: String,
        dataType: String,
        isNullable: Bool,
        isPrimaryKey: Bool,
        defaultValue: String? = nil,
        extra: String? = nil,
        charset: String? = nil,
        collation: String? = nil,
        comment: String? = nil,
        identityKind: IdentityKind? = nil,
        isGenerated: Bool = false,
        allowedValues: [String]? = nil,
        generationExpression: String? = nil,
        generationKind: GenerationKind? = nil
    ) {
        self.name = name
        self.dataType = dataType
        self.isNullable = isNullable
        self.isPrimaryKey = isPrimaryKey
        self.defaultValue = defaultValue
        self.extra = extra
        self.charset = charset
        self.collation = collation
        self.comment = comment
        self.identityKind = identityKind
        self.isGenerated = isGenerated
        self.allowedValues = allowedValues
        self.generationExpression = generationExpression
        self.generationKind = generationKind
    }
}

/// Information about a table-level CHECK constraint.
///
/// `columns` is empty on engines whose catalog cannot answer it (MySQL, MariaDB, SQLite); the
/// grid shows the cell blank there rather than guessing from the expression text.
struct CheckConstraintInfo: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let expression: String
    let columns: [String]
    let isValidated: Bool

    init(name: String, expression: String, columns: [String] = [], isValidated: Bool = true) {
        self.name = name
        self.expression = expression
        self.columns = columns
        self.isValidated = isValidated
    }
}

/// Information about a table index
struct IndexInfo: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let columns: [String]
    let isUnique: Bool
    let isPrimary: Bool
    let type: String  // BTREE, HASH, FULLTEXT, etc.
    let columnPrefixes: [String: Int]?
    let whereClause: String?

    init(
        name: String,
        columns: [String],
        isUnique: Bool,
        isPrimary: Bool,
        type: String,
        columnPrefixes: [String: Int]? = nil,
        whereClause: String? = nil
    ) {
        self.name = name
        self.columns = columns
        self.isUnique = isUnique
        self.isPrimary = isPrimary
        self.type = type
        self.columnPrefixes = columnPrefixes
        self.whereClause = whereClause
    }
}

/// Information about a foreign key relationship
struct ForeignKeyInfo: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let column: String
    let referencedTable: String
    let referencedColumn: String
    let referencedSchema: String?
    let onDelete: String  // CASCADE, SET NULL, RESTRICT, NO ACTION
    let onUpdate: String

    init(
        name: String,
        column: String,
        referencedTable: String,
        referencedColumn: String,
        referencedSchema: String? = nil,
        onDelete: String = "NO ACTION",
        onUpdate: String = "NO ACTION"
    ) {
        self.name = name
        self.column = column
        self.referencedTable = referencedTable
        self.referencedColumn = referencedColumn
        self.referencedSchema = referencedSchema
        self.onDelete = onDelete
        self.onUpdate = onUpdate
    }
}

struct TriggerInfo: Identifiable, Hashable {
    let name: String
    let timing: String
    let event: String
    let statement: String
    let enabled: Bool?

    /// A trigger name is unique per table on PostgreSQL and Oracle, not per schema, so a
    /// database-wide list keyed on the name alone loses one of any two tables that agree on it.
    let table: String?
    let schema: String?
    let orientation: String?

    /// The runnable CREATE TRIGGER text. `statement` is only the action body.
    let definition: String?
    let attributes: [ObjectAttribute]

    var id: String {
        [schema, table, name].compactMap { $0?.isEmpty == false ? $0 : nil }.joined(separator: ".")
    }

    init(
        name: String,
        timing: String,
        event: String,
        statement: String,
        enabled: Bool? = nil,
        table: String? = nil,
        schema: String? = nil,
        orientation: String? = nil,
        definition: String? = nil,
        attributes: [ObjectAttribute] = []
    ) {
        self.name = name
        self.timing = timing
        self.event = event
        self.statement = statement
        self.enabled = enabled
        self.table = table
        self.schema = schema
        self.orientation = orientation
        self.definition = definition
        self.attributes = attributes
    }

    var qualifiedName: String {
        guard let table, !table.isEmpty else { return name }
        return "\(table).\(name)"
    }
}

/// Connection status
enum ConnectionStatus: Equatable, Sendable {
    case disconnected
    case connecting
    case connected
    case error(String)

    var isConnected: Bool {
        if case .connected = self { return true }
        return false
    }
}
