import Foundation
@testable import TablePro
import Testing

@Suite("WhatsNewContent")
struct WhatsNewContentTests {
    @Test("Takes the title from the leading heading and keeps the rest as body")
    func parsesTitleAndBody() {
        let content = WhatsNewContent.parse("""
        # TablePro 0.75.0

        Map view for results holding a geometry column.
        Row-number gutter held at the left edge.
        """)

        #expect(content.title == "TablePro 0.75.0")
        #expect(content.paragraphs.count == 2)
        #expect(String(content.paragraphs[0].characters).contains("Map view"))
        #expect(String(content.paragraphs[1].characters).contains("Row-number gutter"))
    }

    /// Each line is its own point, so a whole-document parse that merged them into one block
    /// would be wrong.
    @Test("Keeps each line as its own paragraph")
    func keepsLinesSeparate() {
        let content = WhatsNewContent.parse("# T\n\nOne.\nTwo.\nThree.\n")

        #expect(content.paragraphs.count == 3)
    }

    @Test("Renders inline markdown rather than showing its syntax")
    func rendersInlineMarkdown() {
        let content = WhatsNewContent.parse("# T\n\n**Map view** for `geometry` columns.\n")
        let rendered = String(content.paragraphs[0].characters)

        #expect(!rendered.contains("**"))
        #expect(!rendered.contains("`"))
        #expect(rendered.contains("Map view"))
        #expect(rendered.contains("geometry"))
    }

    @Test("Falls back to a pointer when the file holds nothing")
    func fallsBackWhenEmpty() {
        let content = WhatsNewContent.parse("")

        #expect(!content.title.isEmpty)
        #expect(content.paragraphs.count == 1)
    }

    @Test("A file with only a heading still offers something to read")
    func headingOnly() {
        let content = WhatsNewContent.parse("# TablePro 0.75.0\n")

        #expect(content.title == "TablePro 0.75.0")
        #expect(content.paragraphs.count == 1)
    }

    /// The file is generated by scripts/generate-whats-new.sh and shipped in the bundle, so a
    /// build where it is missing or unreadable must still open a usable window.
    @Test("The bundled file parses into something displayable")
    func bundledFileParses() {
        let content = WhatsNewContent.bundled

        #expect(!content.title.isEmpty)
        #expect(!content.paragraphs.isEmpty)
    }
}
