//
//  StagedWriteScopeTests.swift
//  TableProTests
//

import Foundation
@testable import TablePro
import Testing

@Suite("Staged write scope")
struct StagedWriteScopeTests {
    private let connectionId = UUID()

    private func scope(_ database: String, schema: String? = nil) -> DatabaseScope {
        DatabaseScope(connectionId: connectionId, database: database, schema: schema)
    }

    /// The statements are generated by the session's own driver before anything is pinned, and a
    /// driver that qualifies from its live connection writes the database it is on into the
    /// statement. Queue a drop while browsing `staging`, switch to `production` and press Save, and
    /// the plan used to run the queued name against production and drop the production table.
    @Test("A queue for a database the connection has left is refused")
    func queueOutsideTheBrowsedDatabaseIsRefused() {
        #expect(throws: DatabaseError.self) {
            try StagedWriteScope.resolve(
                tabScope: scope("production", schema: "public"),
                browseDatabase: "production",
                stagedDatabases: ["staging"],
                includesRowEdits: false
            )
        }
    }

    /// The tab in front is free to be somewhere else. Only the driver that generated the
    /// statements has to be where they will run.
    @Test("A queue for the browsed database runs there even when the tab is elsewhere")
    func queueRunsInTheBrowsedDatabase() throws {
        let resolved = try StagedWriteScope.resolve(
            tabScope: scope("production", schema: "public"),
            browseDatabase: "staging",
            stagedDatabases: ["staging"],
            includesRowEdits: false
        )

        #expect(resolved.database == "staging")
    }

    /// A schema belongs to the database it was read from. Carrying the tab's into another database
    /// would qualify every statement with a schema that need not exist there, and each queued
    /// statement qualifies its own anyway.
    @Test("Crossing databases drops the tab's schema")
    func crossingDatabasesDropsTheSchema() throws {
        let resolved = try StagedWriteScope.resolve(
            tabScope: scope("production", schema: "public"),
            browseDatabase: "staging",
            stagedDatabases: ["staging"],
            includesRowEdits: false
        )

        #expect(resolved.schema == nil)
    }

    @Test("A queue in the tab's own database keeps the tab's scope whole")
    func sameDatabaseKeepsTheTabScope() throws {
        let tab = scope("app", schema: "reporting")
        let resolved = try StagedWriteScope.resolve(
            tabScope: tab,
            browseDatabase: "app",
            stagedDatabases: ["app"],
            includesRowEdits: false
        )

        #expect(resolved == tab)
    }

    @Test("Nothing queued leaves the tab's scope alone")
    func emptyQueueUsesTheTabScope() throws {
        let tab = scope("app", schema: "public")
        let resolved = try StagedWriteScope.resolve(
            tabScope: tab,
            browseDatabase: "reporting",
            stagedDatabases: [],
            includesRowEdits: true
        )

        #expect(resolved == tab)
    }

    /// An engine with no databases queues rows that name none, which is not the same as naming a
    /// different one.
    @Test("A queue that names no database runs where the tab does")
    func unnamedDatabaseUsesTheTabScope() throws {
        let tab = scope("", schema: nil)
        let resolved = try StagedWriteScope.resolve(
            tabScope: tab,
            browseDatabase: "",
            stagedDatabases: [""],
            includesRowEdits: false
        )

        #expect(resolved == tab)
    }

    /// One plan runs on one driver, so this has no answer. Refusing is what stops the save landing
    /// half of the queue in the wrong place.
    @Test("A queue spanning two databases is refused")
    func spanningQueueIsRefused() {
        #expect(throws: DatabaseError.self) {
            try StagedWriteScope.resolve(
                tabScope: scope("app"),
                browseDatabase: "app",
                stagedDatabases: ["staging", "production"],
                includesRowEdits: false
            )
        }
    }

    @Test("Row edits on one database and a queue on another are refused")
    func rowEditsAcrossTheQueueAreRefused() {
        #expect(throws: DatabaseError.self) {
            try StagedWriteScope.resolve(
                tabScope: scope("production"),
                browseDatabase: "staging",
                stagedDatabases: ["staging"],
                includesRowEdits: true
            )
        }
    }
}
