#!/usr/bin/env bash
#
# Check the catalog shapes OracleColumnDefault relies on against a real Oracle server.
#
# The app reads a column's default from ALL_TAB_COLS.DATA_DEFAULT and decides what to show from
# facts measured once on 23ai and written down in OracleColumnDefault: the text keeps the trailing
# whitespace and any comment typed after the value, no default is SQL NULL while DEFAULT NULL is
# the text `null`, an identity column stores its sequence and a virtual column its expression, and
# restating a DEFAULT ON NULL value without its ON NULL switches the semantics off. Nothing else
# checks those against a server, and getting one wrong is silent: a default that is not shown, or
# one written back as something else. So this creates one column of each shape, reads it through
# the same OracleCoreConnection and OracleSchemaQueries the app uses, writes every decoded value
# back the way the Structure tab does, and reads it again.
#
# Usage:
#   scripts/check-oracle-column-defaults.sh [host] [port] [service] [user] [password]
#
# Defaults suit a throwaway Oracle Free container:
#   docker run -d --name oracle-probe -p 1521:1521 -e ORACLE_PASSWORD=probe_pw \
#     -e APP_USER=probe -e APP_USER_PASSWORD=probe_pw gvenzl/oracle-free:23-slim-faststart
#
# The user needs CREATE TABLE. Every object it creates is prefixed TP_COLDEF_ and dropped again.
# Exits non-zero on a disagreement, 3 when a prerequisite is missing.

set -uo pipefail

HOST="${1:-127.0.0.1}"
PORT="${2:-1521}"
SERVICE="${3:-FREEPDB1}"
USER_NAME="${4:-probe}"
PASSWORD="${5:-probe_pw}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ -z "${DEVELOPER_DIR:-}" ]; then
    for candidate in /Applications/Xcode-beta.app /Applications/Xcode.app; do
        if [ -d "$candidate/Contents/Developer" ]; then
            export DEVELOPER_DIR="$candidate/Contents/Developer"
            break
        fi
    done
fi
command -v swift > /dev/null || {
    echo "swift not found" >&2
    exit 3
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/Sources/Probe"

cat > "$WORK/Package.swift" <<EOF
// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "Probe",
    platforms: [.macOS(.v14)],
    dependencies: [.package(path: "$ROOT/Packages/TableProOracle")],
    targets: [
        .executableTarget(
            name: "Probe",
            dependencies: [.product(name: "TableProOracleCore", package: "TableProOracle")]
        )
    ]
)
EOF

cat > "$WORK/Sources/Probe/main.swift" <<'EOF'
import Foundation
import TableProOracleCore

let arguments = CommandLine.arguments
let connection = OracleCoreConnection(options: OracleConnectionOptions(
    host: arguments[1], port: Int(arguments[2]) ?? 1_521, user: arguments[4], password: arguments[5],
    identifierMode: .service, serviceName: arguments[3]
))

do {
    try await connection.connect()
} catch {
    print("cannot connect: \(error)")
    exit(3)
}
guard let release = connection.serverRelease else {
    print("the login reply carried no server release")
    exit(3)
}
guard release.hasIdentityColumns else {
    print("Oracle \(release.major) has no identity or DEFAULT ON NULL columns; this check needs 12.1 or later")
    exit(3)
}
print("Oracle \(release.major)")

var disagreements = 0

@MainActor
func check(_ holds: Bool, _ claim: String) {
    print("\(holds ? "ok  " : "FAIL") \(claim)")
    if !holds { disagreements += 1 }
}

func run(_ sql: String) async -> String? {
    do {
        _ = try await connection.executeQuery(sql)
        return nil
    } catch {
        return String(describing: error)
    }
}

@MainActor
func rows(_ sql: String) async -> [[OracleRawCell]] {
    do {
        return try await connection.executeQuery(sql).rows
    } catch {
        print("FAIL \(sql.prefix(80)): \(error)")
        disagreements += 1
        return []
    }
}

let table = "TP_COLDEF_T"
let schema = await rows(OracleSchemaQueries.currentSchema).first?.first?.stringValue ?? arguments[4].uppercased()
_ = await run("DROP TABLE \(table) PURGE")

let onUpdateColumn = release.hasDefaultOnNullForUpdate
    ? ",\n  C_ONUPD VARCHAR2(10) DEFAULT ON NULL FOR INSERT AND UPDATE 'u'"
    : ""
let create = """
    CREATE TABLE \(table) (
      C_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      C_SEVEN NUMBER DEFAULT 7
      , C_NULL VARCHAR2(5) DEFAULT null,
      C_NONE VARCHAR2(5),
      C_SYS DATE DEFAULT sysdate,
      C_QUOTE VARCHAR2(10) DEFAULT 'it''s',
      C_VIRT NUMBER GENERATED ALWAYS AS (C_SEVEN + 1) VIRTUAL,
      C_ONNULL VARCHAR2(10) DEFAULT ON NULL 'x',
      C_COMMENT NUMBER DEFAULT 9 -- note
      , C_QQ VARCHAR2(20) DEFAULT q'[a -- b]',
      C_INV VARCHAR2(10) INVISIBLE DEFAULT 'hid',
      C_KEY VARCHAR2(10) DEFAULT 'k' NOT NULL\(onUpdateColumn)
    )
    """
if let failure = await run(create) {
    print("cannot create \(table): \(failure)")
    exit(3)
}
_ = await run("CREATE INDEX TP_COLDEF_FBI ON \(table) (UPPER(C_QUOTE))")

func dictionary() async -> [String: [OracleRawCell]] {
    let sql = """
        SELECT COLUMN_NAME, DATA_DEFAULT, IDENTITY_COLUMN, VIRTUAL_COLUMN, DEFAULT_ON_NULL, NULLABLE
        FROM USER_TAB_COLS WHERE TABLE_NAME = '\(table)'
        """
    var byName: [String: [OracleRawCell]] = [:]
    for row in await rows(sql) {
        if let name = row.first?.stringValue { byName[name] = row }
    }
    return byName
}

let raw = await dictionary()
func stored(_ column: String) -> String? { raw[column]?[1].stringValue }
func flag(_ column: String, _ index: Int) -> String? { raw[column]?[index].stringValue }

check(stored("C_SEVEN")?.hasPrefix("7") == true && stored("C_SEVEN") != "7",
      "DATA_DEFAULT keeps the whitespace typed after the value: \(String(reflecting: stored("C_SEVEN")))")
check(stored("C_NULL") == "null", "DEFAULT null is stored as the text typed: \(String(reflecting: stored("C_NULL")))")
check(raw["C_NONE"] != nil && stored("C_NONE") == nil, "no default is SQL NULL")
check(stored("C_COMMENT")?.contains("-- note") == true,
      "a comment typed after the value is stored with it: \(String(reflecting: stored("C_COMMENT")))")
check(flag("C_ID", 2) == "YES" && stored("C_ID")?.lowercased().contains("nextval") == true,
      "an identity column stores its sequence: \(String(reflecting: stored("C_ID")))")
check(flag("C_VIRT", 3) == "YES" && stored("C_VIRT") != nil,
      "a virtual column stores its expression: \(String(reflecting: stored("C_VIRT")))")
check(flag("C_ONNULL", 4) == "YES" && stored("C_ONNULL") == "'x'",
      "a DEFAULT ON NULL column stores the value alone and flags DEFAULT_ON_NULL")

let catalogOrder = await rows("""
    SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER = '\(schema)' AND TABLE_NAME = '\(table)' ORDER BY COLUMN_ID
    """).compactMap { $0.first?.stringValue }

func appColumns() async -> [OracleColumnRow] {
    await rows(OracleSchemaQueries.columns(schema: schema, table: table, release: release))
        .compactMap(OracleSchemaQueries.parseColumnRow)
}

let columns = await appColumns()
check(columns.map(\.name) == catalogOrder,
      "the app reads exactly the rows ALL_TAB_COLUMNS returns: \(columns.map(\.name))")
let bulk = await rows(OracleSchemaQueries.allColumns(schema: schema, release: release))
    .compactMap(OracleSchemaQueries.parseTableColumnRow)
    .filter { $0.table == table }
    .map(\.column)
check(bulk == columns, "the bulk read decodes every column the same way")

var expected: [String: String?] = [
    "C_ID": nil, "C_SEVEN": "7", "C_NULL": "NULL", "C_NONE": nil, "C_SYS": "sysdate", "C_QUOTE": "'it''s'",
    "C_VIRT": nil, "C_ONNULL": "ON NULL 'x'", "C_COMMENT": "9", "C_QQ": "q'[a -- b]'", "C_INV": "'hid'",
    "C_KEY": "'k'"
]
if release.hasDefaultOnNullForUpdate {
    expected["C_ONUPD"] = "ON NULL FOR INSERT AND UPDATE 'u'"
}
for column in columns {
    let want = expected[column.name] ?? nil
    check(column.defaultValue == want,
          "\(column.name) decodes to \(String(reflecting: want)): \(String(reflecting: column.defaultValue))")
}

for column in columns {
    guard let value = column.defaultValue else { continue }
    let quoted = OracleSchemaQueries.quoteIdentifier(column.name)
    if let failure = await run("ALTER TABLE \(table) MODIFY (\(quoted) DEFAULT \(value))") {
        check(false, "writing \(column.name) back as DEFAULT \(value): \(failure)")
    }
}
let afterWrite = await appColumns()
check(afterWrite == columns, "every decoded default written back reads back unchanged")
check(await dictionary()["C_ONNULL"]?[4].stringValue == "YES", "writing ON NULL 'x' back keeps DEFAULT ON NULL")

_ = await run("ALTER TABLE \(table) MODIFY (C_ONNULL DEFAULT 'y')")
let plainRestatement = await dictionary()["C_ONNULL"]
check(plainRestatement?[4].stringValue == "NO" && plainRestatement?[5].stringValue == "Y",
      "restating a DEFAULT ON NULL value without ON NULL switches it off and makes the column nullable")

let restated = await run("ALTER TABLE \(table) MODIFY (C_KEY NOT NULL)")
check(restated?.contains("01442") == true, "restating NOT NULL on a NOT NULL column fails with ORA-01442")

_ = await run("ALTER TABLE \(table) MODIFY (C_SEVEN DEFAULT NULL)")
check(await appColumns().first { $0.name == "C_SEVEN" }?.defaultValue == "NULL",
      "DEFAULT NULL written over a default reads back as NULL")

for other in [OracleServerRelease(major: 11), OracleServerRelease(major: 19)] {
    let sql = OracleSchemaQueries.columns(schema: schema, table: table, release: other)
    do {
        let names = try await connection.executeQuery(sql).rows.compactMap(OracleSchemaQueries.parseColumnRow).map(\.name)
        print("info the Oracle \(other.major) form runs here and returns \(names.count) columns")
    } catch {
        check(false, "the Oracle \(other.major) form runs on this server: \(error)")
    }
}

_ = await run("DROP TABLE \(table) PURGE")

print(disagreements == 0 ? "The column default shapes match this server." : "\(disagreements) disagreement(s).")
exit(disagreements == 0 ? 0 : 1)
EOF

echo "Building the probe against Packages/TableProOracle (the first build takes a minute)"
(cd "$WORK" && swift build -c debug > "$WORK/build.log" 2>&1) || {
    grep -E "error:" "$WORK/build.log" | head -20 >&2
    exit 3
}
"$WORK/.build/debug/Probe" "$HOST" "$PORT" "$SERVICE" "$USER_NAME" "$PASSWORD" 2> /dev/null
