import Foundation
@testable import TableProMobile
import TableProModels
import XCTest

final class PostgreSQLDriverCatalogTests: XCTestCase {
    private static let schema = "ios_pg_catalog_test"
    private static let foreignDataWrapper = "ios_pg_catalog_test_fdw"

    private var driver: PostgreSQLDriver?

    private static func loadTestConfig() -> [String: String]? {
        let env = ProcessInfo.processInfo.environment
        if env["POSTGRES_TEST_HOST"] != nil {
            return env
        }
        let fallbackPath = env["POSTGRES_TEST_CONFIG_PATH"] ?? "/tmp/postgres-test.json"
        guard let data = FileManager.default.contents(atPath: fallbackPath),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: String]
        else { return nil }
        return json
    }

    override func setUp() async throws {
        guard let config = Self.loadTestConfig() else {
            throw XCTSkip("POSTGRES_TEST_HOST not set and /tmp/postgres-test.json not found, skipping integration tests")
        }
        let driver = PostgreSQLDriver(
            host: config["POSTGRES_TEST_HOST"] ?? "127.0.0.1",
            port: Int(config["POSTGRES_TEST_PORT"] ?? "5432") ?? 5_432,
            user: config["POSTGRES_TEST_USER"] ?? "postgres",
            password: config["POSTGRES_TEST_PASSWORD"] ?? "",
            database: config["POSTGRES_TEST_DATABASE"] ?? "postgres"
        )
        try await driver.connect()
        self.driver = driver
        for statement in Self.fixture {
            _ = try await driver.execute(query: statement)
        }
    }

    override func tearDown() async throws {
        if let driver {
            _ = try? await driver.execute(query: "DROP SCHEMA IF EXISTS \(Self.schema) CASCADE")
            _ = try? await driver.execute(query: "DROP FOREIGN DATA WRAPPER IF EXISTS \(Self.foreignDataWrapper) CASCADE")
            try await driver.disconnect()
        }
        driver = nil
    }

    private static let fixture = [
        "DROP SCHEMA IF EXISTS \(schema) CASCADE",
        "CREATE SCHEMA \(schema)",
        "CREATE TABLE \(schema).t (id int PRIMARY KEY, a int, b text, email text, tenant_id int, n int GENERATED BY DEFAULT AS IDENTITY)",
        "CREATE INDEX t_mixed ON \(schema).t (tenant_id, lower(email))",
        "CREATE INDEX t_include ON \(schema).t (a) INCLUDE (b)",
        "CREATE INDEX t_order ON \(schema).t (b, a)",
        "CREATE UNIQUE INDEX t_partial ON \(schema).t (a) WHERE a > 0",
        "CREATE INDEX t_hash ON \(schema).t USING hash (email)",
        "CREATE VIEW \(schema).v AS SELECT id FROM \(schema).t",
        "CREATE MATERIALIZED VIEW \(schema).mv AS SELECT id AS mv_id, lower(email) AS mv_expr, b::varchar(20) AS label FROM \(schema).t",
        "CREATE UNIQUE INDEX mv_id_key ON \(schema).mv (mv_id)",
        "CREATE INDEX mv_expr_idx ON \(schema).mv (lower(mv_expr))"
    ]

    private static let foreignTableFixture = [
        "DROP FOREIGN DATA WRAPPER IF EXISTS \(foreignDataWrapper) CASCADE",
        "CREATE FOREIGN DATA WRAPPER \(foreignDataWrapper)",
        "CREATE SERVER ios_pg_catalog_test_server FOREIGN DATA WRAPPER \(foreignDataWrapper)",
        "CREATE FOREIGN TABLE \(schema).ft (a int) SERVER ios_pg_catalog_test_server"
    ]

    func testMaterializedViewIsListedAsOne() async throws {
        let driver = try XCTUnwrap(driver)

        let tables = try await driver.fetchTables(schema: Self.schema)

        XCTAssertEqual(tables.map(\.name), ["mv", "t", "v"])
        XCTAssertEqual(tables.map(\.type), [.materializedView, .table, .view])
    }

    func testForeignTableIsListedAsOne() async throws {
        let driver = try XCTUnwrap(driver)
        do {
            for statement in Self.foreignTableFixture {
                _ = try await driver.execute(query: statement)
            }
        } catch {
            throw XCTSkip("Creating a foreign data wrapper needs a superuser: \(error.localizedDescription)")
        }

        let tables = try await driver.fetchTables(schema: Self.schema)

        XCTAssertEqual(tables.map(\.name), ["ft", "mv", "t", "v"])
        XCTAssertEqual(tables.first?.type, .foreignTable)
        XCTAssertEqual(tables.first?.type.allowsDrop, false)
    }

    func testIndexesKeepKeyOrderExpressionsIncludeColumnsAndPredicates() async throws {
        let driver = try XCTUnwrap(driver)

        let indexes = try await driver.fetchIndexes(table: "t", schema: Self.schema)
        let byName = Dictionary(uniqueKeysWithValues: indexes.map { ($0.name, $0) })

        XCTAssertEqual(indexes.first?.name, "t_pkey")
        XCTAssertEqual(byName["t_mixed"]?.columns, ["tenant_id", "lower(email)"])
        XCTAssertEqual(byName["t_include"]?.columns, ["a"])
        XCTAssertEqual(byName["t_include"]?.includedColumns, ["b"])
        XCTAssertEqual(byName["t_order"]?.columns, ["b", "a"])
        XCTAssertEqual(byName["t_partial"]?.whereClause, "(a > 0)")
        XCTAssertEqual(byName["t_hash"]?.type, "HASH")
    }

    func testMaterializedViewHasColumnsAndIndexes() async throws {
        let driver = try XCTUnwrap(driver)

        let columns = try await driver.fetchColumns(table: "mv", schema: Self.schema)
        let indexes = try await driver.fetchIndexes(table: "mv", schema: Self.schema)

        XCTAssertEqual(columns.map(\.name), ["mv_id", "mv_expr", "label"])
        XCTAssertEqual(columns.map(\.typeName), ["integer", "text", "character varying"])
        XCTAssertEqual(columns.last?.characterMaxLength, 20)
        XCTAssertEqual(Set(indexes.map(\.name)), ["mv_id_key", "mv_expr_idx"])
        XCTAssertEqual(indexes.first { $0.name == "mv_expr_idx" }?.columns, ["lower(mv_expr)"])
        XCTAssertEqual(
            driver.columnReadSupport,
            PostgreSQLColumnReadSupport(identityColumns: true, materializedViewColumns: true)
        )
    }

    func testTableColumnsKeepTheirPrimaryKeyAndIdentity() async throws {
        let driver = try XCTUnwrap(driver)

        let columns = try await driver.fetchColumns(table: "t", schema: Self.schema)

        XCTAssertEqual(columns.map(\.name), ["id", "a", "b", "email", "tenant_id", "n"])
        XCTAssertEqual(columns.first?.isPrimaryKey, true)
        XCTAssertEqual(columns.first?.isNullable, false)
        XCTAssertEqual(columns.last?.isAutoIncrement, true)
    }
}
