//
//  SchemaMetadataGeneratedColumnTests.swift
//  TableProTests
//
//  The generated-column flag has to survive the driver-to-app schema parse, or
//  the grid and the statement generator never learn a column is computed.
//

import Foundation
import TableProPluginKit
@testable import TablePro
import Testing

@MainActor @Suite("Schema metadata generated columns")
struct SchemaMetadataGeneratedColumnTests {
    private func makeSchema(_ columns: [ColumnInfo]) -> FetchedTableSchema {
        FetchedTableSchema(columns: columns, foreignKeys: nil, approximateRowCount: nil)
    }

    @Test("A generated column is carried into the parsed metadata")
    func generatedColumnIsParsed() {
        let schema = makeSchema([
            ColumnInfo(name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true),
            ColumnInfo(name: "name", dataType: "TEXT", isNullable: true, isPrimaryKey: false),
            ColumnInfo(
                name: "full_name",
                dataType: "TEXT",
                isNullable: true,
                isPrimaryKey: false,
                isGenerated: true
            )
        ])

        let parsed = QueryExecutor.parseSchemaMetadata(schema)

        #expect(parsed.generatedColumns == ["full_name"])
        #expect(parsed.primaryKeyColumns == ["id"])
    }

    @Test("A table with no generated columns parses to an empty set")
    func noGeneratedColumns() {
        let schema = makeSchema([
            ColumnInfo(name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true)
        ])

        #expect(QueryExecutor.parseSchemaMetadata(schema).generatedColumns.isEmpty)
    }

    @Test("ColumnInfo defaults to not generated")
    func columnInfoDefaultsToNotGenerated() {
        let column = ColumnInfo(name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true)
        #expect(!column.isGenerated)
        #expect(column.identityKind == nil)
    }

    /// PostgreSQL reports an identity column with a null `column_default`, so the kind is the only
    /// thing that says the server fills the column in.
    @Test("Both identity kinds are carried into the parsed metadata")
    func identityKindIsParsed() {
        let schema = makeSchema([
            ColumnInfo(
                name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true,
                identityKind: .always
            ),
            ColumnInfo(
                name: "code", dataType: "INT", isNullable: false, isPrimaryKey: false,
                identityKind: .byDefault
            ),
            ColumnInfo(name: "name", dataType: "TEXT", isNullable: true, isPrimaryKey: false)
        ])

        let parsed = QueryExecutor.parseSchemaMetadata(schema)

        #expect(parsed.columnIdentity == ["id": .always, "code": .byDefault])
    }

    /// A GENERATED ALWAYS identity column rejects an explicit INSERT value and an UPDATE alike, so
    /// it belongs in the set the statement generator refuses to write, next to a stored generated
    /// column. A GENERATED BY DEFAULT one accepts both and must stay writable.
    @Test("Only an ALWAYS identity column joins the non-writable set")
    func alwaysIdentityIsNotWritable() {
        let schema = makeSchema([
            ColumnInfo(
                name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true,
                identityKind: .always
            ),
            ColumnInfo(
                name: "code", dataType: "INT", isNullable: false, isPrimaryKey: false,
                identityKind: .byDefault
            )
        ])

        #expect(QueryExecutor.parseSchemaMetadata(schema).generatedColumns == ["id"])
    }
}

/// The metadata a rerun inherits is captured when the cache decision is made, not read back when the
/// result lands. Reading it late read whichever result was active by then, so selecting a pinned
/// result mid-flight made the rerun adopt that other result's identity and non-writable sets.
@MainActor @Suite("Cached schema metadata snapshot")
struct CachedSchemaMetadataTests {
    private func rows(
        columnIdentity: [String: IdentityKind] = [:],
        generatedColumns: Set<String> = [],
        hasAuthoritativeSchema: Bool = true
    ) -> TableRows {
        TableRows.from(
            queryRows: [],
            columns: ["id", "name"],
            columnTypes: [],
            columnDefaults: ["name": "'anon'"],
            columnEnumValues: ["name": ["a"]],
            columnNullable: ["name": true],
            columnComments: ["name": "the name"],
            columnIdentity: columnIdentity,
            generatedColumns: generatedColumns,
            hasAuthoritativeSchema: hasAuthoritativeSchema,
            foreignKeysFetched: true
        )
    }

    @Test("The snapshot carries every write-relevant field")
    func snapshotCarriesWriteFields() {
        let cached = ParsedSchemaMetadata.cached(
            rows: rows(columnIdentity: ["id": .always], generatedColumns: ["id"]),
            primaryKeyColumns: ["id"]
        )

        #expect(cached.columnIdentity == ["id": .always])
        #expect(cached.generatedColumns == ["id"])
        #expect(cached.primaryKeyColumns == ["id"])
        #expect(cached.isAuthoritative)
        #expect(cached.columnForeignKeys != nil)
    }

    /// `foreignKeysFetched` is what tells the tab its arrows have arrived. Claiming they had when
    /// they had not would let the metadata fetch be skipped for good.
    @Test("Unfetched foreign keys stay absent rather than becoming an empty answer")
    func unfetchedForeignKeysStayNil() {
        var unfetched = rows()
        unfetched.foreignKeysFetched = false

        #expect(ParsedSchemaMetadata.cached(rows: unfetched, primaryKeyColumns: []).columnForeignKeys == nil)
    }

    @Test("A snapshot of rows built from result metadata is not authoritative")
    func inheritsNonAuthoritative() {
        let cached = ParsedSchemaMetadata.cached(
            rows: rows(hasAuthoritativeSchema: false),
            primaryKeyColumns: []
        )

        #expect(!cached.isAuthoritative)
    }
}

/// Only the table's own schema names the columns the server owns. A result set reports far less, so
/// treating its silence as "this table owns nothing" staged NULL into an identity column.
@MainActor @Suite("Schema metadata authoritativeness")
struct SchemaMetadataAuthoritativenessTests {
    @Test("A parsed table schema is authoritative")
    func parsedSchemaIsAuthoritative() {
        let schema = FetchedTableSchema(
            columns: [ColumnInfo(name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true)],
            foreignKeys: nil,
            approximateRowCount: nil
        )

        #expect(QueryExecutor.parseSchemaMetadata(schema).isAuthoritative)
    }

    @Test("Result-set metadata is not authoritative")
    func inlineMetadataIsNotAuthoritative() {
        let parsed = QueryExecutor.inlineMetadata(
            from: [ResultColumnMeta(isPrimaryKey: true, isNullable: false, isAutoIncrement: true)],
            columns: ["id"]
        )

        #expect(parsed?.isAuthoritative == false)
    }

    /// The result set does report that the server allocates the column, and that much is worth
    /// carrying: it is the difference between pre-filling DEFAULT and pre-filling NULL. It never
    /// says whether an explicit value would be refused, so the writable kind is the safe reading.
    @Test("An auto-increment result column is carried as a writable identity")
    func inlineMetadataCarriesAutoIncrement() {
        let parsed = QueryExecutor.inlineMetadata(
            from: [
                ResultColumnMeta(isPrimaryKey: true, isNullable: false, isAutoIncrement: true),
                ResultColumnMeta(isPrimaryKey: false, isNullable: true, isAutoIncrement: false),
            ],
            columns: ["id", "name"]
        )

        #expect(parsed?.columnIdentity == ["id": .byDefault])
        #expect(parsed?.generatedColumns.isEmpty == true)
    }
}
