//
//  SchemaMetadataGeneratedColumnTests.swift
//  TableProTests
//
//  The generated-column flag has to survive the driver-to-app schema parse, or
//  the grid and the statement generator never learn a column is computed.
//

import Foundation
import TableProPluginKit
@testable import TablePro
import Testing

@MainActor @Suite("Schema metadata generated columns")
struct SchemaMetadataGeneratedColumnTests {
    private func makeSchema(_ columns: [ColumnInfo]) -> FetchedTableSchema {
        FetchedTableSchema(columns: columns, foreignKeys: nil, approximateRowCount: nil)
    }

    @Test("A generated column is carried into the parsed metadata")
    func generatedColumnIsParsed() {
        let schema = makeSchema([
            ColumnInfo(name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true),
            ColumnInfo(name: "name", dataType: "TEXT", isNullable: true, isPrimaryKey: false),
            ColumnInfo(
                name: "full_name",
                dataType: "TEXT",
                isNullable: true,
                isPrimaryKey: false,
                isGenerated: true
            )
        ])

        let parsed = QueryExecutor.parseSchemaMetadata(schema)

        #expect(parsed.generatedColumns == ["full_name"])
        #expect(parsed.primaryKeyColumns == ["id"])
    }

    @Test("A table with no generated columns parses to an empty set")
    func noGeneratedColumns() {
        let schema = makeSchema([
            ColumnInfo(name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true)
        ])

        #expect(QueryExecutor.parseSchemaMetadata(schema).generatedColumns.isEmpty)
    }

    @Test("ColumnInfo defaults to not generated")
    func columnInfoDefaultsToNotGenerated() {
        let column = ColumnInfo(name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true)
        #expect(!column.isGenerated)
        #expect(column.identityKind == nil)
    }

    /// PostgreSQL reports an identity column with a null `column_default`, so the kind is the only
    /// thing that says the server fills the column in.
    @Test("Both identity kinds are carried into the parsed metadata")
    func identityKindIsParsed() {
        let schema = makeSchema([
            ColumnInfo(
                name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true,
                identityKind: .always
            ),
            ColumnInfo(
                name: "code", dataType: "INT", isNullable: false, isPrimaryKey: false,
                identityKind: .byDefault
            ),
            ColumnInfo(name: "name", dataType: "TEXT", isNullable: true, isPrimaryKey: false)
        ])

        let parsed = QueryExecutor.parseSchemaMetadata(schema)

        #expect(parsed.columnIdentity == ["id": .always, "code": .byDefault])
    }

    /// A GENERATED ALWAYS identity column rejects an explicit INSERT value and an UPDATE alike, so
    /// it belongs in the set the statement generator refuses to write, next to a stored generated
    /// column. A GENERATED BY DEFAULT one accepts both and must stay writable.
    @Test("Only an ALWAYS identity column joins the non-writable set")
    func alwaysIdentityIsNotWritable() {
        let schema = makeSchema([
            ColumnInfo(
                name: "id", dataType: "INT", isNullable: false, isPrimaryKey: true,
                identityKind: .always
            ),
            ColumnInfo(
                name: "code", dataType: "INT", isNullable: false, isPrimaryKey: false,
                identityKind: .byDefault
            )
        ])

        #expect(QueryExecutor.parseSchemaMetadata(schema).generatedColumns == ["id"])
    }
}
