//
//  OracleColumnStatements.swift
//  OracleDriverPlugin
//

import Foundation
import TableProPluginKit

/// The `ALTER TABLE` that turns one column into another.
///
/// `MODIFY` names only what changed, because Oracle leaves every omitted attribute as it was and restating an unchanged
/// one is not neutral. Measured on 23ai: restating `NOT NULL` on a column that already has it fails the whole
/// statement with ORA-01442, so a default could never be changed on a `NOT NULL` column; and restating `NULL` next to
/// a `DEFAULT ON NULL` fails with ORA-30665. Restating a type is not neutral either: a length without its unit takes
/// the session's `NLS_LENGTH_SEMANTICS`, so an unchanged type is left out too.
///
/// The type is written as it was given. A type change is still detected without regard to case, but folding the
/// written type would turn a quoted mixed-case object type such as `"Hunt_Mixed"` into a name that does not exist.
internal enum OracleColumnStatements {
    /// Auto-increment is `GENERATED BY DEFAULT ON NULL AS IDENTITY`, not `ALWAYS`, so an explicit key from a copy or
    /// an import still inserts (ORA-32795 otherwise). An identity takes no `DEFAULT`, and `ON NULL` makes it NOT NULL.
    internal static func definition(
        _ column: PluginColumnDefinition,
        inlinePrimaryKey: Bool,
        supportsIdentity: Bool,
        quote: (String) -> String
    ) -> String {
        var parts = [quote(column.name), column.dataType]
        if column.autoIncrement && supportsIdentity {
            parts.append("GENERATED BY DEFAULT ON NULL AS IDENTITY")
        } else {
            if let defaultValue = column.defaultValue {
                parts.append("DEFAULT \(defaultValue)")
            }
            if !column.isNullable {
                parts.append("NOT NULL")
            }
        }
        if inlinePrimaryKey && column.isPrimaryKey {
            parts.append("PRIMARY KEY")
        }
        return parts.joined(separator: " ")
    }

    internal static func commentStatements(qualifiedTable: String, columns: [PluginColumnDefinition]) -> [String] {
        columns.compactMap { column in
            guard let comment = column.comment, !comment.isEmpty else { return nil }
            return OracleObjectQueries.columnCommentStatement(
                qualifiedTable: qualifiedTable, column: column.name, comment: comment
            )
        }
    }

    internal static func modify(
        qualifiedTable: String,
        oldColumn: PluginColumnDefinition,
        newColumn: PluginColumnDefinition,
        quote: (String) -> String
    ) -> String? {
        var statements: [String] = []
        if oldColumn.name != newColumn.name {
            statements.append(
                "ALTER TABLE \(qualifiedTable) RENAME COLUMN \(quote(oldColumn.name)) TO \(quote(newColumn.name))"
            )
        }
        if let change = attributeChange(from: oldColumn, to: newColumn, quote: quote) {
            statements.append("ALTER TABLE \(qualifiedTable) MODIFY (\(change))")
        }
        return statements.isEmpty ? nil : statements.joined(separator: ";\n")
    }

    /// No default is written as `DEFAULT NULL`, because Oracle has no way to take a default away: the dictionary then
    /// reports the text `NULL`, which reads back as the `NULL` default.
    private static func attributeChange(
        from oldColumn: PluginColumnDefinition,
        to newColumn: PluginColumnDefinition,
        quote: (String) -> String
    ) -> String? {
        let typeChanged = oldColumn.dataType.caseInsensitiveCompare(newColumn.dataType) != .orderedSame
        let nullabilityChanged = oldColumn.isNullable != newColumn.isNullable
        let defaultChanged = oldColumn.defaultValue != newColumn.defaultValue
        guard typeChanged || nullabilityChanged || defaultChanged else { return nil }

        var parts = [quote(newColumn.name)]
        if typeChanged {
            parts.append(newColumn.dataType)
        }
        if defaultChanged {
            parts.append("DEFAULT \(newColumn.defaultValue ?? "NULL")")
        }
        if nullabilityChanged {
            parts.append(newColumn.isNullable ? "NULL" : "NOT NULL")
        }
        return parts.joined(separator: " ")
    }
}
